sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/ActionPlan__c.object-meta.xml
<CustomObject>
    <description>Action Plan instance. Contains Action Plan Tasks.</description>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/fields/Contact__c.field-meta.xml
<CustomField>
	<fullName>Contact__c</fullName>
	<deleteConstraint>SetNull</deleteConstraint>
	<label>Contact</label>
	<referenceTo>Contact</referenceTo>
	<relationshipLabel>Action Plans</relationshipLabel>
	<relationshipName>Action_Plans</relationshipName>
	<type>Lookup</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/fields/Lead__c.field-meta.xml
<CustomField>
	<fullName>Lead__c</fullName>
	<deleteConstraint>SetNull</deleteConstraint>
	<label>Lead</label>
	<referenceTo>Lead</referenceTo>
	<relationshipLabel>Action Plans</relationshipLabel>
	<relationshipName>Action_Plans</relationshipName>
	<type>Lookup</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/APTask__c.object-meta.xml
<CustomObject>
    <description>Action Plan Task - belongs to Action Plan</description>
    <label>ActionPlan Task</label>
    <nameField>
        <label>ActionPlan Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ActionPlan Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Action_Plan__c.field-meta.xml
<CustomField>
	<fullName>Action_Plan__c</fullName>
	<label>Action Plan</label>
	<referenceTo>ActionPlan__c</referenceTo>
	<relationshipName>apTasks1</relationshipName>
	<relationshipOrder>0</relationshipOrder>
	<type>MasterDetail</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/ActivityDate__c.field-meta.xml
<CustomField>
	<fullName>ActivityDate__c</fullName>
	<description>The Due Date for this AP Task - will be copied to the Task Due Date</description>
	<label>Due Date</label>
	<type>Date</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Comments__c.field-meta.xml
<CustomField>
	<fullName>Comments__c</fullName>
	<label>Comments</label>
	<description>Text to be copied to Task Description</description>
	<length>32000</length>
	<type>LongTextArea</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Controller__c.field-meta.xml
<CustomField>
	<fullName>Controller__c</fullName>
	<deleteConstraint>SetNull</deleteConstraint>
	<label>Controlling Task</label>
	<referenceTo>APTask__c</referenceTo>
	<relationshipLabel>Dependent AP Tasks</relationshipLabel>
	<relationshipName>Dependent_AP_Tasks</relationshipName>
	<type>Lookup</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Dependent__c.field-meta.xml
<CustomField>
	<fullName>Dependent__c</fullName>
	<defaultValue>&quot;None&quot;</defaultValue>
	<label>Dependent</label>
	<length>255</length>
	<description>The TaskIndex of the controlling task</description>
	<type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Minutes_Reminder__c.field-meta.xml
<CustomField>
	<fullName>Minutes_Reminder__c</fullName>
	<inlineHelpText>Minutes after midnight to show Task reminder</inlineHelpText>
	<description>Minutes after midnight to show Task reminder. Not shown to user - use the Time_Reminder formula instead.</description>
	<label>Minutes Reminder</label>
	<length>4</length>
	<type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Unrestricted picklist so can include any custom task priorities the customer may use.</description>
    <inlineHelpText>The default priority of the new task</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Reminder__c.field-meta.xml
<CustomField>
	<fullName>Reminder__c</fullName>
	<defaultValue>false</defaultValue>
	<label>Reminder</label>
	<type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/SendEmail__c.field-meta.xml
<CustomField>
    <fullName>SendEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Send Email Notification of Task creation.</description>
    <label>Send Email</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Status__c.field-meta.xml
<CustomField>
	<fullName>Status__c</fullName>
	<description>Initial Task Status. Depends on Record Type, so is unrestricted picklist.</description>
	<label>Status</label>
	<type>Picklist</type>
	<valueSet>
		<valueSetDefinition>
			<value>
				<fullName>Not Started</fullName>
				
				<label>Not Started</label>
			</value>
			<value>
				<fullName>In Progress</fullName>
				
				<label>In Progress</label>
			</value>
			<value>
				<fullName>Waiting on someone else</fullName>
				
				<label>Waiting on someone else</label>
			</value>
			<value>
				<fullName>Deferred</fullName>
				
				<label>Deferred</label>
			</value>
			<value>
				<fullName>Completed</fullName>
				
				<label>Completed</label>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Type__c.field-meta.xml
<CustomField>
	<fullName>Type__c</fullName>
	<label>Type</label>
	<description>Task Type</description>
	<type>Picklist</type>
	<valueSet>
		<valueSetDefinition>
			<value>
				<fullName>Call</fullName>
			</value>
			<value>
				<fullName>Email</fullName>
			</value>
			<value>
				<fullName>Mail</fullName>
			</value>
			<value>
				<fullName>Meeting</fullName>
			</value>
			<value>
				<fullName>Misc</fullName>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If this field is not required, leaving it blank will assign the task to the related record owner.</inlineHelpText>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>APTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/classes/ActionPlansBatchTaskBuilder.cls
/*
Action Plans v4
David Schach 2022

Action Plans v3
Force.com Labs 2011
http://appexchange.salesforce.com/listingDetail?listingId=a0N30000003HcINEA0

BSD 3-Clause License

Copyright (c) 2022, salesforce.com, inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/**
 * When we have more than one task to create, run it in batch context for higher limits
 * @author Rodrigo Birriel
 * @author {@link [David Schach](https://github.com/dschach)}
 * @since v3
 * @group Asynchronous
 */
public without sharing class ActionPlansBatchTaskBuilder implements Database.Batchable<SObject>, Database.Stateful {
	/**
	 * The list of `APTask__c` Ids passed to this class
	 */
	private List<Id> aptIds;
	/**
	 * Constructor accepts APTask IDs
	 * @param taskIDs List of `APTask__c` IDs
	 */
	public ActionPlansBatchTaskBuilder(List<Id> taskIDs) {
		aptIds = taskIDs;
	}

	/**
	 * QueryLocator: Select the List of `APTask__c`.
	 * @param  bc BatchableContext for start method
	 * @return    `Database.QueryLocator`
	 */
	public Database.QueryLocator start(Database.BatchableContext bc) {
		//Add Action Plan custom object reference Field.
		String soql =
			'SELECT User__c, Type__c, Subject__c, Status__c, SendEmail__c, Reminder__c, Minutes_Reminder__c,' +
			'Priority__c, Name, Id, Dependent__c, Comments__c, ActivityDate__c,' +
			'Action_Plan__c, ';

		for (String s : ActionPlansUtilities.getCustomRelationshipFields()) {
			soql += 'Action_Plan__r.' + s + ', ';
		}

		soql += ' Controller__c FROM APTask__c WHERE Id IN :aptIds';

		return Database.getQueryLocator(soql);
	}

	/**
	 * Eecute this method multiple times, by default on batches of 200 records
	 * @param bc    BatchableContext
	 * @param data  The list of SObjects to act on
	 */
	public void execute(Database.BatchableContext bc, List<SObject> data) {
		List<Task> myTasksWithEmail = new List<Task>();
		List<Task> myTasksWithOutEmail = new List<Task>();
		List<APTask__c> apTasks = new List<APTask__c>();

		for (SObject obj : data) {
			APTask__c oneData = (APTask__c) obj;
			apTasks.add(oneData);
		}

		//Now run this magic!
		for (APTask__c apTask : apTasks) {
			// check if task exists already
			Task t = new Task();
			t.Subject = apTask.Subject__c;
			t.Priority = apTask.Priority__c;
			t.OwnerId = apTask.User__c;
			t.TaskAPTask__c = apTask.Id;

			// fake link to AP Task Template
			if (apTask.Comments__c != null) {
				t.Description = apTask.Comments__c;
			}

			//set reminder based on user's default reminder setting
			if (apTask.Reminder__c == true && apTask.ActivityDate__c != null) {
				t.isReminderSet = apTask.Reminder__c;

				t.ReminderDateTime = Datetime.newInstance(apTask.ActivityDate__c.year(), apTask.ActivityDate__c.month(), apTask.ActivityDate__c.day(), 0, 0, 0);
				t.ReminderDateTime = t.ReminderDateTime.addMinutes(Integer.valueOf(apTask.Minutes_Reminder__c));
			}
			ActionPlan__c ap = apTask.Action_Plan__r;

			//link to Action Plan's Related To Object
			for (String s : ActionPlansUtilities.getCustomRelationshipFields()) {
				String f = s;
				if (!f.equalsIgnoreCase(ActionPlansUtilities.namespacePrefix + 'Contact__c') && !f.equalsIgnoreCase(ActionPlansUtilities.namespacePrefix + 'Lead__c') && ap.get(f) != null) {
					t.WhatId = (Id) ap.get(f);
					break;
				}
			}

			if (apTask.Action_Plan__r.Contact__c != null) {
				t.WhoId = apTask.Action_Plan__r.Contact__c;
			} else if (apTask.Action_Plan__r.Lead__c != null) {
				t.WhoId = apTask.Action_Plan__r.Lead__c;
			}

			t.Type = apTask.Type__c;
			t.ActivityDate = apTask.ActivityDate__c;

			if (apTask.Dependent__c == null || apTask.Dependent__c == 'None') {
				if (apTask.SendEmail__c == true) {
					myTasksWithEmail.add(t);
				} else {
					myTasksWithOutEmail.add(t);
				}
			}
		}

		Database.DMLOptions dmlo = new Database.DMLOptions();
		Database.DMLOptions dmlo2 = new Database.DMLOptions();

		if (myTasksWithEmail.size() > 0) {
			dmlo.EmailHeader.triggerUserEmail = true;
			Database.insert(myTasksWithEmail, dmlo);
		}

		if (myTasksWithOutEmail.size() > 0) {
			dmlo2.EmailHeader.triggerUserEmail = false;
			Database.insert(myTasksWithOutEmail, dmlo2);
		}
	}

	/**
	 * Required finish method - we could do something here like send a platform event or notify the user that the batch is complete
	 * @param  bc BatchableContext
	 */
	// prettier-ignore
	public void finish(Database.BatchableContext bc) {} //NOPMD
}