sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/ActionPlan__c.object-meta.xml
<CustomObject>
    <description>Action Plan instance. Contains Action Plan Tasks.</description>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/fields/Action_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the Action Plan was created from a Template, it is related via this field</description>
    <label>Action Plan Template</label>
    <referenceTo>ActionPlanTemplate__c</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>ActionPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/ActionPlanTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Action Plans. Contains Action Plan Template Tasks</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Action Plan Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/APTask__c.object-meta.xml
<CustomObject>
    <description>Action Plan Task - belongs to Action Plan</description>
    <label>ActionPlan Task</label>
    <nameField>
        <label>ActionPlan Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ActionPlan Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Action_Plan__c.field-meta.xml
<CustomField>
	<fullName>Action_Plan__c</fullName>
	<label>Action Plan</label>
	<referenceTo>ActionPlan__c</referenceTo>
	<relationshipName>apTasks1</relationshipName>
	<relationshipOrder>0</relationshipOrder>
	<type>MasterDetail</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/APTemplateTask__c.object-meta.xml
<CustomObject>
    <description>Action Plan Template Task - belongs to Action Plan Template</description>
    <label>ActionPlanTemplate Task</label>
    <nameField>
        <label>Action Plan Template Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ActionPlanTemplate Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Action_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Template__c</fullName>
    <label>Action Plan Template</label>
    <referenceTo>ActionPlanTemplate__c</referenceTo>
	<description>The parent Action Plan Template</description>
    <relationshipLabel>Action Plan Template Tasks</relationshipLabel>
    <relationshipName>aptTasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/classes/tests/ActionPlansRedirectTest.cls
/*
Action Plans v4
David Schach 2022
https://appexchange.salesforce.com/appxListingDetail?listingId=a0N4V00000Gg6NVUAZ

Copyright (c) 2022, salesforce.com, inc.
All rights reserved.
SPDX-License-Identifier: BSD-3-Clause
For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
*/
/**
 * Test for Redirect Visualforce Controller
 * @author {@link [David Schach](https://github.com/dschach)}
 * @since 2022
 * @since 2023 System.assert to Assert class + error messages
 * @see ActionPlansRedirect
 * @group Tests
 */
@IsTest
private class ActionPlansRedirectTest {
	@TestSetup
	private static void makeData() {
		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();

		ActionPlanTemplate__c apTemplate = testUtil.createNewActionPlanTemplate(2);
		Assert.areNotEqual(null, apTemplate.Id, 'We should have created an ActionPlan Template');
		ActionPlan__c actionPlan = testUtil.createNewActionPlan('contact', 2, null);
		Assert.areNotEqual(null, actionPlan.Id, 'We should have created an ActionPlan');
	}

	@IsTest
	private static void aPTaskRedirect() {
		Test.startTest();
		APTask__c apt = [SELECT Id, Action_Plan__c FROM APTask__c LIMIT 1];

		Test.setCurrentPage(Page.ActionPlanTaskOverride);
		ActionPlansRedirect apr = new ActionPlansRedirect(new ApexPages.StandardController(apt));

		PageReference pr = apr.redirect();
		Test.stopTest();

		Pagereference cp = pr;
		Assert.isFalse(cp.getURL().containsIgnoreCase(apt.Id), 'The redirect URL should not contain the APTask Id');
		System.debug('CurrentPage ' + cp.getURL());
		Assert.isTrue(cp.getURL().containsIgnoreCase(apt.Action_Plan__c), 'The redirect URL should contain the Action Plan Id');
	}

	@IsTest
	private static void aPTTaskRedirect() {
		Test.startTest();
		APTemplateTask__c apttt = [SELECT Id, Action_Plan_Template__c FROM APTemplateTask__c LIMIT 1];

		Test.setCurrentPage(Page.ActionPlanTemplateTaskOverride);
		ActionPlansRedirect apr = new ActionPlansRedirect(new ApexPages.StandardController(apttt));

		PageReference pr = apr.redirect();
		Test.stopTest();

		Pagereference cp = pr;
		Assert.isFalse(cp.getURL().containsIgnoreCase(apttt.Id), 'The redirect URL should not contain the APTemplateTask Id');
		System.debug('CurrentPage ' + cp.getURL());
		Assert.isTrue(cp.getURL().containsIgnoreCase(apttt.Action_Plan_Template__c), 'The redirect URL should contain the Action Plan Template Id');
	}

	@IsTest
	private static void actionPlanChangeOwner() {
		ActionPlan__c actionPlan = [SELECT Id FROM ActionPlan__c LIMIT 1];
		Test.setCurrentPage(Page.ActionPlanAPOwnerChange);
		ActionPlansRedirect apr = new ActionPlansRedirect(new ApexPages.StandardController(actionPlan));
		PageReference pr = apr.save();
		Assert.isTrue(pr.getURL().containsIgnoreCase(actionPlan.Id), 'Should have put Id in view page URL');

		Test.startTest();
		Test.setCurrentPage(Page.ActionPlanAPOwnerChange);
		apr = new ActionPlansRedirect(new ApexPages.StandardController(actionPlan));
		pr = apr.cancel();
		Test.stopTest();
		Assert.isTrue(pr.getURL().containsIgnoreCase(actionPlan.Id), 'Should have put Id in view page URL');
	}

	@IsTest
	private static void actionPlanTemplateChangeOwner() {
		ActionPlanTemplate__c actionPlanTemplate = [SELECT Id FROM ActionPlanTemplate__c LIMIT 1];
		Test.setCurrentPage(Page.ActionPlanAPTOwnerChange);
		ActionPlansRedirect apr = new ActionPlansRedirect(new ApexPages.StandardController(actionPlanTemplate));
		PageReference pr = apr.cancel();
		Assert.isTrue(pr.getURL().containsIgnoreCase(actionPlanTemplate.Id), 'Should have put Id in view page URL');

		Test.startTest();
		Test.setCurrentPage(Page.ActionPlanAPTOwnerChange);
		apr = new ActionPlansRedirect(new ApexPages.StandardController(actionPlanTemplate));
		pr = apr.save();
		Test.stopTest();

		Assert.isTrue(pr.getURL().containsIgnoreCase(actionPlanTemplate.Id), 'Should have put Id in view page URL');
	}
}