sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/ActionPlan__c.object-meta.xml
<CustomObject>
    <description>Action Plan instance. Contains Action Plan Tasks.</description>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/fields/Action_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the Action Plan was created from a Template, it is related via this field</description>
    <label>Action Plan Template</label>
    <referenceTo>ActionPlanTemplate__c</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>ActionPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/ActionPlanTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Action Plans. Contains Action Plan Template Tasks</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Action Plan Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/APTask__c.object-meta.xml
<CustomObject>
    <description>Action Plan Task - belongs to Action Plan</description>
    <label>ActionPlan Task</label>
    <nameField>
        <label>ActionPlan Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ActionPlan Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Action_Plan__c.field-meta.xml
<CustomField>
	<fullName>Action_Plan__c</fullName>
	<label>Action Plan</label>
	<referenceTo>ActionPlan__c</referenceTo>
	<relationshipName>apTasks1</relationshipName>
	<relationshipOrder>0</relationshipOrder>
	<type>MasterDetail</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/APTemplateTask__c.object-meta.xml
<CustomObject>
    <description>Action Plan Template Task - belongs to Action Plan Template</description>
    <label>ActionPlanTemplate Task</label>
    <nameField>
        <label>Action Plan Template Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ActionPlanTemplate Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Action_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Template__c</fullName>
    <label>Action Plan Template</label>
    <referenceTo>ActionPlanTemplate__c</referenceTo>
	<description>The parent Action Plan Template</description>
    <relationshipLabel>Action Plan Template Tasks</relationshipLabel>
    <relationshipName>aptTasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/classes/ActionPlansRedirect.cls
/*
Action Plans v4
David Schach 2022
https://appexchange.salesforce.com/appxListingDetail?listingId=a0N4V00000Gg6NVUAZ

Copyright (c) 2022, salesforce.com, inc.
All rights reserved.
SPDX-License-Identifier: BSD-3-Clause
For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

*/
/**
 * Visualforce controller for a redirect page to allow override of object actions
 * @author {@link [David Schach](https://github.com/dschach)}
 * @since 2022
 * @group Visualforce
 */
public with sharing class ActionPlansRedirect {
	private APTask__c actionPlanTask;
	private APTemplateTask__c actionPlanTemplateTask;
	private ActionPlan__c actionPlan;
	private ActionPlanTemplate__c actionPlanTemplate;
	private Id parentId;
	private Id recordId;
	/**
	 * Related object name so this page can work for multiple SObject Types
	 */
	public String objName { get; private set; }

	/**
	 * Extension Constructor
	 * <br>Gets the SObjectType and returns the correct object to display the correct values
	 * @param  controller Standard Controller. Accepts any SObject
	 */
	public ActionPlansRedirect(ApexPages.StandardController controller) {
		Id recordId = controller.getId();

		this.objName = recordId.getSObjectType().getDescribe().getLocalName().toLowerCase();

		switch on objName {
			when 'aptask__c' {
				actionPlanTask = (APTask__c) controller.getRecord();
				parentId = actionPlanTask.Action_Plan__c;
			}
			when 'aptemplatetask__c' {
				actionPlanTemplateTask = (APTemplateTask__c) controller.getRecord();
				parentId = actionPlanTemplateTask.Action_Plan_Template__c;
			}
			when 'actionplan__c' {
				actionPlan = (ActionPlan__c) controller.getRecord();
				parentId = actionPlan.Id;
			}
			when 'actionplantemplate__c' {
				actionPlanTemplate = (ActionPlanTemplate__c) controller.getRecord();
				parentId = actionPlanTemplate.Id;
			}
		}
	}

	/**
	 * Change the relevant record owner, and then call cancel so we go back to the record page
	 * @return {@link ActionPlansRedirect.cancel}
	 */
	public PageReference save() {
		if (objName.equalsIgnoreCase('ActionPlan__c')) {
			update actionPlan;
		}
		if (objName.equalsIgnoreCase('ActionPlanTemplate__c')) {
			update actionPlanTemplate;
		}
		return cancel();
	}

	/**
	 * Go back to view the relevant record
	 * @return   `PageReference` for the parent record
	 */
	public PageReference cancel() {
		PageReference viewPage;
		if (objName.equalsIgnoreCase('ActionPlan__c')) {
			update actionPlan;
			viewPage = Page.ActionPlanDetail;
			viewPage.getParameters().put('id', actionPlan.Id);
		}
		if (objName.equalsIgnoreCase('ActionPlanTemplate__c')) {
			update actionPlanTemplate;
			viewPage = Page.ActionPlanTemplateDetail;
			viewPage.getParameters().put('id', actionPlanTemplate.Id);
		}
		viewPage.setRedirect(true);
		return viewpage;
	}

	/**
	 * Show the view page for either the Action Plan or the Action Plan Template
	 * @return   `PageReference` by recordId ('/' + parentId)
	 */
	public Pagereference redirect() {
		Pagereference pr = new Pagereference('/' + parentId);
		pr.setRedirect(true);
		return pr;
	}
}