sfdx-source/LabsActionPlans/main/default/objects/Action_Plans_Settings__c/Action_Plans_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The basic settings for the Action Plans App</description>
    <label>Action Plans Settings</label>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/Action_Plans_Settings__c/fields/Chatter_Object_Brag__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Object_Brag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enable Chatter FeedItem post when a New Action Plan for a record is created.</description>
    <inlineHelpText>Enable Chatter Object Brag when a New Action Plan for an object is created.</inlineHelpText>
    <label>Enable Chatter Post</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/Action_Plans_Settings__c/fields/Unassigned_Task_Assigned_to_Owner__c.field-meta.xml
<CustomField>
    <fullName>Unassigned_Task_Assigned_to_Owner__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field defaults to TRUE because we assume that no matter who triggers the invoked Action Plan creation, the tasks will most likely be assigned to the owner of the parent record.</description>
    <inlineHelpText>If the Task is Unassigned in the Template, and this is Checked, the assigned User for the Task is the Owner of the Record. If this setting is unchecked, the assigned User for the Task is the Current User.</inlineHelpText>
    <label>Unassigned Task Assigned to Record Owner</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/ActionPlan__c.object-meta.xml
<CustomObject>
    <description>Action Plan instance. Contains Action Plan Tasks.</description>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/fields/Contact__c.field-meta.xml
<CustomField>
	<fullName>Contact__c</fullName>
	<deleteConstraint>SetNull</deleteConstraint>
	<label>Contact</label>
	<referenceTo>Contact</referenceTo>
	<relationshipLabel>Action Plans</relationshipLabel>
	<relationshipName>Action_Plans</relationshipName>
	<type>Lookup</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/fields/Contract__c.field-meta.xml
<CustomField>
	<fullName>Contract__c</fullName>
	<deleteConstraint>SetNull</deleteConstraint>
	<label>Contract</label>
	<referenceTo>Contract</referenceTo>
	<relationshipLabel>Action Plans</relationshipLabel>
	<relationshipName>Action_Plans</relationshipName>
	<type>Lookup</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/fields/SkipDay__c.field-meta.xml
<CustomField>
	<fullName>SkipDay__c</fullName>
	<description>Skip Day</description>
	<label>Default Weekend Due Dates To</label>
	<type>Picklist</type>
	<valueSet>
		<controllingField>SkipWeekends__c</controllingField>
		<restricted>true</restricted>
		<valueSetName>SkipDay</valueSetName>
	</valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/fields/SkipWeekends__c.field-meta.xml
<CustomField>
	<fullName>SkipWeekends__c</fullName>
	<defaultValue>false</defaultValue>
	<description>If selected, tasks included in an Action Plan will not be given a Due Date that falls on a weekend or non-working day.</description>
	<inlineHelpText>Automatically reschedules a task that would fall on a non-working day to either before or after.</inlineHelpText>
	<label>Avoid Weekends For Due Dates</label>
	<type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>The Start Date of the Action Plan</description>
    <inlineHelpText>The Start Date of the Action Plan</inlineHelpText>
    <label>Plan Start Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/fields/TaskRecordTypeID__c.field-meta.xml
<CustomField>
    <fullName>TaskRecordTypeID__c</fullName>
    <description>The Record Type Id (not label) of the Tasks for this Action Plan</description>
    <label>Tasks Record Type</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/ActionPlanTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Action Plans. Contains Action Plan Template Tasks</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Action Plan Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/fields/SkipDay__c.field-meta.xml
<CustomField>
	<fullName>SkipDay__c</fullName>
	<description>If a Due Date lands on a weekend it should be pushed to this day.</description>
	<inlineHelpText>If a Due Date lands on a weekend it should be pushed to this day.</inlineHelpText>
	<label>Default Weekend Due Dates To</label>
	<type>Picklist</type>
	<valueSet>
		<controllingField>SkipWeekends__c</controllingField>
		<restricted>true</restricted>
		<valueSetName>SkipDay</valueSetName>
	</valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/fields/SkipWeekends__c.field-meta.xml
<CustomField>
	<fullName>SkipWeekends__c</fullName>
	<defaultValue>false</defaultValue>
	<description>If selected, tasks included in an Action Plan will not be given a Due Date that falls on a weekend.</description>
	<inlineHelpText>Automatically reschedules a task that would fall on a Saturday or a Sunday to either a Monday or Friday so you can skip weekends when calculating activity start dates.</inlineHelpText>
	<label>Avoid Weekends For Due Dates</label>
	<type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/fields/TaskRecordTypeID__c.field-meta.xml
<CustomField>
	<fullName>TaskRecordTypeID__c</fullName>
	<label>Tasks Record Type</label>
	<length>18</length>
	<type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/APTask__c.object-meta.xml
<CustomObject>
    <description>Action Plan Task - belongs to Action Plan</description>
    <label>ActionPlan Task</label>
    <nameField>
        <label>ActionPlan Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ActionPlan Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Action_Plan__c.field-meta.xml
<CustomField>
	<fullName>Action_Plan__c</fullName>
	<label>Action Plan</label>
	<referenceTo>ActionPlan__c</referenceTo>
	<relationshipName>apTasks1</relationshipName>
	<relationshipOrder>0</relationshipOrder>
	<type>MasterDetail</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/ActivityDate__c.field-meta.xml
<CustomField>
	<fullName>ActivityDate__c</fullName>
	<description>The Due Date for this AP Task - will be copied to the Task Due Date</description>
	<label>Due Date</label>
	<type>Date</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Controller__c.field-meta.xml
<CustomField>
	<fullName>Controller__c</fullName>
	<deleteConstraint>SetNull</deleteConstraint>
	<label>Controlling Task</label>
	<referenceTo>APTask__c</referenceTo>
	<relationshipLabel>Dependent AP Tasks</relationshipLabel>
	<relationshipName>Dependent_AP_Tasks</relationshipName>
	<type>Lookup</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/DaysFromStart__c.field-meta.xml
<CustomField>
    <fullName>DaysFromStart__c</fullName>
    <inlineHelpText>This value determines the due date of the task. For tasks with no dependency, the task&apos;s due date will be offset from the plan start date. For tasks with a dependency, the due date will be offset from the expected due date of the task on which it depends.</inlineHelpText>
    <label>Days After</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Dependent__c.field-meta.xml
<CustomField>
	<fullName>Dependent__c</fullName>
	<defaultValue>&quot;None&quot;</defaultValue>
	<label>Dependent</label>
	<length>255</length>
	<description>The TaskIndex of the controlling task</description>
	<type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Unrestricted picklist so can include any custom task priorities the customer may use.</description>
    <inlineHelpText>The default priority of the new task</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Reminder__c.field-meta.xml
<CustomField>
	<fullName>Reminder__c</fullName>
	<defaultValue>false</defaultValue>
	<label>Reminder</label>
	<type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Status__c.field-meta.xml
<CustomField>
	<fullName>Status__c</fullName>
	<description>Initial Task Status. Depends on Record Type, so is unrestricted picklist.</description>
	<label>Status</label>
	<type>Picklist</type>
	<valueSet>
		<valueSetDefinition>
			<value>
				<fullName>Not Started</fullName>
				
				<label>Not Started</label>
			</value>
			<value>
				<fullName>In Progress</fullName>
				
				<label>In Progress</label>
			</value>
			<value>
				<fullName>Waiting on someone else</fullName>
				
				<label>Waiting on someone else</label>
			</value>
			<value>
				<fullName>Deferred</fullName>
				
				<label>Deferred</label>
			</value>
			<value>
				<fullName>Completed</fullName>
				
				<label>Completed</label>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Type__c.field-meta.xml
<CustomField>
	<fullName>Type__c</fullName>
	<label>Type</label>
	<description>Task Type</description>
	<type>Picklist</type>
	<valueSet>
		<valueSetDefinition>
			<value>
				<fullName>Call</fullName>
			</value>
			<value>
				<fullName>Email</fullName>
			</value>
			<value>
				<fullName>Mail</fullName>
			</value>
			<value>
				<fullName>Meeting</fullName>
			</value>
			<value>
				<fullName>Misc</fullName>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If this field is not required, leaving it blank will assign the task to the related record owner.</inlineHelpText>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>APTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/APTemplateTask__c.object-meta.xml
<CustomObject>
    <description>Action Plan Template Task - belongs to Action Plan Template</description>
    <label>ActionPlanTemplate Task</label>
    <nameField>
        <label>Action Plan Template Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ActionPlanTemplate Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/DaysFromStart__c.field-meta.xml
<CustomField>
	<fullName>DaysFromStart__c</fullName>
	<inlineHelpText>This value determines the due date of the task. For tasks with no dependency, the task&apos;s due date will be offset from the plan start date. For tasks with a dependency, the due date will be offset from the expected due date of the task on which it depends.</inlineHelpText>
	<label>Days After</label>
	<precision>3</precision>
	<description>How many days from the plan start date or due date of the controlling task will this task be due?</description>
	<scale>0</scale>
	<type>Number</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Dependent__c.field-meta.xml
<CustomField>
    <fullName>Dependent__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <label>Dependent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Priority__c.field-meta.xml
<CustomField>
	<fullName>Priority__c</fullName>
	<label>Priority</label>
	<type>Picklist</type>
	<valueSet>
		<valueSetDefinition>
			<value>
				<fullName>High</fullName>
				
				<label>High</label>
			</value>
			<value>
				<fullName>Normal</fullName>
				
				<default>true</default>
				<label>Normal</label>
			</value>
			<value>
				<fullName>Low</fullName>
				
				<label>Low</label>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Subject__c.field-meta.xml
<CustomField>
	<fullName>Subject__c</fullName>
	<label>Subject</label>
	<description>Task Subject</description>
	<length>255</length>
	<required>true</required>
	<type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Type__c.field-meta.xml
<CustomField>
	<fullName>Type__c</fullName>
	<label>Task Type</label>
	<length>255</length>
	<description>Task Type</description>
	<type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/User__c.field-meta.xml
<CustomField>
	<fullName>User__c</fullName>
	<deleteConstraint>SetNull</deleteConstraint>
	<inlineHelpText>The user who will always be assigned this task. Leaving this blank will, depending on Action Plans Settings, assign this task to the related record owner or the running user.</inlineHelpText>
	<label>Assigned To</label>
	<referenceTo>User</referenceTo>
	<relationshipName>APTTasks</relationshipName>
	<type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/SkipDay.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>End of previous week</fullName>
    </customValue>
    <customValue>
        <fullName>Start of next week</fullName>
    </customValue>
    <description>Action Plans: Adjust task due dates to avoid weekends or any other non-working day.</description>
    <masterLabel>Skip Day</masterLabel>
</GlobalValueSet>

sfdx-source/LabsActionPlans/main/default/tests/ActionPlanCreationControllerTest.cls
/*
Action Plans v4
David Schach 2022

Action Plans v3
Force.com Labs 2011
http://appexchange.salesforce.com/listingDetail?listingId=a0N30000003HcINEA0

BSD 3-Clause License

Copyright (c) 2022, salesforce.com, inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
/**
 * Tests for `ActionPlan__c` Create/Edit Visualforce Extension
 * @author {@link [David Schach](https://github.com/dschach)}
 * @group Visualforce
 */
@IsTest
private class ActionPlanCreationControllerTest {
	@TestSetup
	private static void makeData() {
		Action_Plans_Settings__c aps = ActionPlansUtilities.getCustomSetting();
		aps.Chatter_Object_Brag__c = true;
		aps.Unassigned_Task_Assigned_to_Owner__c = true;
		try {
			upsert aps;
		} catch (Exception e) {
			update aps;
		}
	}

	@IsTest
	private static void singleRecordConstructor() {
		Test.startTest();
		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
		ActionPlan__c actionPlan = testUtil.createNewActionPlan('contact', 2);

		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));
		apCreateController.onLoad();
		System.assertEquals(0, apCreateController.getCompleted(), 'New AP should have no completed tasks');
		System.assertNotEquals(null, apCreateController.relatedFieldName, 'should have lazy loaded relatedFieldName');

		apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));
		apCreateController.relatedObjectId();
		apCreateController.save();
		Test.stopTest();
	}

	@IsTest
	private static void constructorTests() {
		Test.startTest();
		Test.setCurrentPage(Page.ActionPlanCreation);

		ApexPages.currentPage().getParameters().put('id', null);
		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(new ActionPlan__c()));
		System.assertNotEquals(null, apCreateController.relatedFieldName, 'should have lazy loaded relatedFieldName');

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
		ActionPlan__c actionPlan = testUtil.createNewActionPlan('contact', 2);

		apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));

		ApexPages.currentPage().getParameters().put('id', null);
		ApexPages.currentPage().getParameters().put('clone', '1');
		apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(new ActionPlan__c()));

		ActionPlanTemplate__c apTemplate = testUtil.createNewActionPlanTemplate(3);

		ApexPages.currentPage().getParameters().put('id', null);
		ApexPages.currentPage().getParameters().put('clone', null);
		ApexPages.currentPage().getParameters().put('templateId', apTemplate.Id);
		apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(new ActionPlan__c()));

		Contact contact = testUtil.createNewContact();

		ApexPages.currentPage().getParameters().put('id', null);
		ApexPages.currentPage().getParameters().put('refId', contact.Id);
		apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(new ActionPlan__c()));
		String refId = apCreateController.refId;
		System.debug(refId);
		String reftype = apCreateController.refType;
		System.debug(reftype);

		apCreateController.refreshRelatedObjectsLookUp();
		apCreateController.getTaskRTPicklistValues();
		apCreateController.getTaskTypes();
		apCreateController.getTaskPriorities();
		apCreateController.getHoursOption();
		apCreateController.getDisplayTemplateLookup();
		apCreateController.getRecordTypeName();

		apCreateController.relatedFieldName = ActionPlansUtilities.namespacePrefix + 'Contract__c';
		apCreateController.relatedFieldName = ActionPlansUtilities.namespacePrefix + 'Case__c';
		apCreateController.relatedFieldName = ActionPlansUtilities.namespacePrefix + 'Contact__c';

		apCreateController.save();

		Test.stopTest();
	}

	@IsTest
	private static void testActionPlanSave() {
		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
		ActionPlan__c ap = testUtil.createNewActionPlan('contact', 3);
		Contact contact = [SELECT Id FROM Contact LIMIT 1];

		ApexPages.currentPage().getParameters().put('id', ap.Id);
		ApexPages.currentPage().getParameters().put('refId', contact.Id);
		ApexPages.currentPage().getParameters().put('refType', 'Contact');

		Test.startTest();

		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(ap));

		apCreateController.actionPlan.name = 'updated name';

		apCreateController.save();

		Test.setCurrentPage(Page.ActionPlanCreation);
		apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(ap));

		apCreateController.actionPlan.SkipWeekends__c = true;
		apCreateController.actionPlan.SkipDay__c = 'End of previous week';

		apCreateController.save();

		Test.stopTest();

		List<ActionPlan__c> results = [SELECT Id, name, Contact__c FROM ActionPlan__c LIMIT 10000];

		System.assert(!results.isEmpty(), 'Action Plan not created');
		System.assert(results.size() == 1, 'Too many Action Plans created');

		apCreateController.cancel();
	}

	@IsTest
	private static void testActionPlanSaveAndNew() {
		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
		ActionPlan__c actionPlan = new ActionPlan__c();

		Contact contact = testUtil.createNewContact();

		actionPlan.Name = testUtil.createRandomWord('Name');
		actionPlan.Contact__c = contact.Id;
		actionPlan.StartDate__c = Date.today();

		APTask__c apTask = new APTask__c();

		apTask.Subject__c = testUtil.createRandomWord('subject');
		apTask.User__c = testUtil.createTestUser().Id;
		apTask.DaysFromStart__c = 2;
		apTask.Type__c = 'Email';
		apTask.Priority__c = 'High';

		ApexPages.currentPage().getParameters().put('id', null);
		ApexPages.currentPage().getParameters().put('refId', contact.Id);
		ApexPages.currentPage().getParameters().put('refType', 'Contact');

		Test.startTest();

		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));

		apCreateController.apTasks = new List<APTask__c>();
		apCreateController.apTasks.add(apTask);
		apCreateController.saveAndNew();
		Test.stopTest();
		List<ActionPlan__c> results = [SELECT Id FROM ActionPlan__c LIMIT 10000];

		System.assert(!results.isEmpty(), 'Action Plan not created');
		System.assert(results.size() == 1, 'ONE Action Plan not created');
		System.debug(results.size() + ' action plans created');
	}

	@IsTest
	private static void testRelateToMultipleContacts() {
		final Integer conCOUNT = 40;
		final Integer apTASKCOUNT = 2;

		List<Contact> contactsList = new List<Contact>();
		for (Integer i = 0; i < conCOUNT; i++) {
			Contact newContact = new Contact(LastName = 'con' + math.rint(math.random() * 100000));
			contactsList.add(newContact);
		}

		Database.DMLOptions dml = new Database.DMLOptions();
		dml.DuplicateRuleHeader.allowSave = true;
		dml.DuplicateRuleHeader.runAsCurrentUser = true;
		Database.insert(contactsList, dml);

		List<Id> conIDs = new List<Id>();
		for (Contact c : contactsList) {
			conIDs.add(c.Id);
		}
		String conIdsList = String.join(conIDs, ',');

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
		ActionPlanTemplate__c apTemplate = testUtil.createNewActionPlanTemplate(apTASKCOUNT);

		Test.startTest();

		Test.setCurrentPage(Page.ActionPlanCreation);

		ApexPages.currentPage().getParameters().put('id', null);
		ApexPages.currentPage().getParameters().put('templateId', apTemplate.Id);
		ApexPages.currentPage().getParameters().put('refId', conIDsList);
		ApexPages.currentPage().getParameters().put('refType', 'Contact');
		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(new ActionPlan__c()));
		System.assert(apCreateController.inVisualforceContext, 'Test should have VF context as true');
		apCreateController.getTasks();
		System.assertEquals(apTASKCOUNT, apCreateController.getTasks().size());
		System.assertEquals(conCOUNT, apCreateController.getNameListSize());

		apCreateController.getTemplateName();
		apCreateController.save();

		Test.stopTest();
		System.assertEquals(apTASKCOUNT, [SELECT COUNT() FROM APTemplateTask__c]);

		System.assertEquals(conCOUNT, [SELECT COUNT() FROM ActionPlan__c], 'Failed to make one AP per contact');
		System.debug('successfully related to ' + conCOUNT + ' Contacts');

		System.assertNotEquals(0, [SELECT COUNT() FROM ActionPlan__c WHERE Contact__c != NULL], 'Should have linked Action Plan to contact');

		System.assertEquals(conCOUNT * apTASKCOUNT, [SELECT COUNT() FROM APTask__c], 'Not enough Action Plan Tasks created');

		System.assertEquals(conCOUNT * apTASKCOUNT, [SELECT COUNT() FROM Task], 'Wrong number of Tasks created');
	}

	@IsTest
	private static void checkCompletedTasks() {
		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
		ActionPlan__c actionPlan = testUtil.createNewActionPlan('account', 2);

		Test.startTest();

		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));
		apCreateController.save();
		apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));

		System.assertEquals(0, apCreateController.getCompleted(), 'Action plan task completed count is incorrect');

		Task openTask = [SELECT Id, IsClosed, Status FROM Task LIMIT 1];
		for (String s : ActionPlansUtilities.getClosedTaskStatuses()) {
			try {
				openTask.Status = s;
				update openTask; //NOPMD
				break;
			} catch (Exception e) {
				continue;
			}
		}
		update openTask;
		Test.stopTest();
		apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));

		Integer numTasksComplete = apCreateController.getCompleted();
		System.assertEquals(1, numTasksComplete, 'The completed Task should have been reflected in the Action Plan');
	}

	@IsTest
	private static void longNameTasks() {
		Test.startTest();

		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
		ActionPlan__c actionPlan = testUtil.createNewActionPlan('account', 2);

		// add code for shortening long record names
		actionPlan.Name = '1234567890123456789012345678901234567890'; // 40 characters
		update actionPlan;
		List<APTask__c> apts = [SELECT Id, Subject__c FROM APTask__c];
		for (APTask__c a : apts) {
			a.Subject__c = 'abcdefghijabcdefghijabcdefghijabcdefghij'; // 40 characters
		}
		update apts;

		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));

		Integer numTasksComplete = apCreateController.getCompleted();

		System.assert(numTasksComplete == 0, 'Action plan task completed is incorrect');

		Test.stopTest();

		for (APTask__c a : [SELECT Id, Name FROM APTask__c]) {
			System.assertEquals(80, a.Name.length(), 'APTask Template name was not updated');
		}
	}

	@IsTest
	private static void testAddNewTask() {
		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();

		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlan__c actionPlan = testUtil.createNewActionPlan('account', 0);

		User ownerUser = testUtil.createTestUser();

		APTask__c apTask = new APTask__c();
		apTask.Action_Plan__c = actionPlan.Id;
		apTask.Subject__c = testUtil.createRandomWord('subject');
		apTask.User__c = ownerUser.Id;
		apTask.DaysFromStart__c = 2;
		apTask.Type__c = 'Email';
		apTask.Priority__c = 'High';
		insert apTask;

		Id defaultTaskRTId = [SELECT Id, TaskRecordTypeID__c FROM ActionPlan__c LIMIT 1].TaskRecordTypeID__c;
		System.debug('defaultTaskRTID: ' + defaultTaskRTId);

		Test.startTest();

		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));
		//apCreateController.apTasks = new List<APTask__c>();
		apCreateController.getTasks();
		System.assertEquals(1, apCreateController.getTasks().size());
		apCreateController.addTask();
		apCreateController.getTasks();
		System.assertEquals(2, apCreateController.getTasks().size());

		ActionPlanCreationController.ApTaskWrapper taskWrap = apCreateController.getTasks()[1];

		taskWrap.apt.Subject__c = testUtil.createRandomWord('subject');
		taskWrap.apt.DaysFromStart__c = 3;
		taskWrap.apt.User__c = ownerUser.Id;
		taskWrap.apt.Priority__c = ActionPlansUtilities.getTaskRecordTypePriorityDefaultValues().get(defaultTaskRTId);
		System.debug('Priority is set to ' + ActionPlansUtilities.getTaskRecordTypePriorityDefaultValues().get(defaultTaskRTId));
		apCreateController.save();

		Test.stopTest();

		System.assertEquals(2, [SELECT COUNT() FROM APTask__c]);
	}

	@IsTest
	private static void testRemoveActionPlanTask() {
		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
		ActionPlan__c actionPlan = testUtil.createNewActionPlan('account', 3);

		Test.startTest();

		ApexPages.currentPage().getParameters().put('id', actionPlan.Id);
		ApexPages.currentPage().getParameters().put('remove', '1');
		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));

		apCreateController.getTasks();
		apCreateController.removeTask();
		apCreateController.save();

		Test.stopTest();

		System.assertEquals(2, [SELECT COUNT() FROM APTask__c]);
	}

	@IsTest
	private static void checkActionPlanTaskList() {
		Test.startTest();

		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
		ActionPlan__c actionPlan = testUtil.createNewActionPlan('account', 2);

		ApexPages.currentPage().getParameters().put('id', actionPlan.Id);
		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));

		List<ActionPlanCreationController.ApTaskWrapper> apTaskList = apCreateController.getTasks();

		System.assert(!apTaskList.isEmpty(), 'Action plan task list is empty');

		Test.stopTest();
	}

	@IsTest
	private static void checkSubjectItems() {
		Integer taskCOUNT = 2;
		Test.startTest();

		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
		ActionPlan__c actionPlan = testUtil.createNewActionPlan('account', taskCOUNT);

		ApexPages.currentPage().getParameters().put('id', actionPlan.Id);
		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));
		apCreateController.apTasks = [
			SELECT
				Type__c,
				Subject__c,
				ActivityDate__c,
				Priority__c,
				Status__c,
				Dependent__c,
				Name,
				User__c,
				User__r.Name,
				Id,
				DaysFromStart__c,
				CreatedById,
				Controller__r.Name,
				Controller__r.Subject__c,
				Controller__c,
				Action_Plan__c,
				Reminder__c,
				SendEmail__c,
				Comments__c
			FROM APTask__c
			WHERE Action_Plan__c = :actionPlan.Id
			ORDER BY createdDate ASC
		];

		List<Selectoption> options = apCreateController.getSubjectItems();

		Test.stopTest();

		System.assert(!options.isEmpty(), 'SELECT options is empty');
		System.assertEquals(taskCOUNT + 1, options.size(), 'incorrect number of select options');
	}

	@IsTest
	private static void testCyclicDependencyTaskSuccess() {
		Test.startTest();

		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();

		ActionPlan__c actionPlan = testUtil.createNewActionPlan('account', 0);

		APTask__c newAPTask1 = new APTask__c();
		APTask__c newAPTask2 = new APTask__c();
		APTask__c newAPTask3 = new APTask__c();

		newAPTask1.Subject__c = testUtil.createRandomWord('subject');
		newAPTask1.DaysFromStart__c = 2;
		newAPTask1.Dependent__c = '2';
		newAPTask1.Type__c = 'Email';
		newAPTask1.Priority__c = 'High';
		newAPTask1.Action_Plan__c = actionPlan.Id;
		upsert newAPTask1;

		newAPTask2.Subject__c = testUtil.createRandomWord('subject');
		newAPTask2.DaysFromStart__c = 2;
		newAPTask2.Dependent__c = 'None';
		newAPTask2.Type__c = 'Email';
		newAPTask2.Priority__c = 'High';
		newAPTask2.Action_Plan__c = actionPlan.Id;
		upsert newAPTask2;

		newAPTask3.Subject__c = testUtil.createRandomWord('subject');
		newAPTask3.DaysFromStart__c = 2;
		newAPTask3.Dependent__c = '1';
		newAPTask3.Type__c = 'Email';
		newAPTask3.Priority__c = 'High';
		newAPTask3.Action_Plan__c = actionPlan.Id;
		upsert newAPTask3;

		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));

		apCreateController.apTasks = new List<APTask__c>();
		apCreateController.apTasks.add(newAPTask1);
		apCreateController.apTasks.add(newAPTask2);
		apCreateController.apTasks.add(newAPTask3);

		apCreateController.save();

		System.assert(apCreateController.getErrorMsg() == '' || String.isBlank(apCreateController.getErrorMsg()));

		Test.stopTest();
	}

	@IsTest
	private static void testCyclicDependencyTasksFail() {
		Test.startTest();

		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();

		ActionPlan__c actionPlan = testUtil.createNewActionPlan('account', 0);

		APTask__c newAPTask1 = new APTask__c();
		APTask__c newAPTask2 = new APTask__c();
		APTask__c newAPTask3 = new APTask__c();

		newAPTask1.Subject__c = testUtil.createRandomWord('subject');
		newAPTask1.DaysFromStart__c = 2;
		newAPTask1.Dependent__c = '2';
		newAPTask1.Type__c = 'Email';
		newAPTask1.Priority__c = 'High';

		newAPTask2.Subject__c = testUtil.createRandomWord('subject');
		newAPTask2.DaysFromStart__c = 2;
		newAPTask2.Dependent__c = '0';
		newAPTask2.Type__c = 'Email';
		newAPTask2.Priority__c = 'High';

		newAPTask3.Subject__c = testUtil.createRandomWord('subject');
		newAPTask3.DaysFromStart__c = 2;
		newAPTask3.Dependent__c = '1';
		newAPTask3.Type__c = 'Email';
		newAPTask3.Priority__c = 'High';

		ApexPages.currentPage().getParameters().put('id', actionPlan.Id);
		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));

		apCreateController.apTasks = new List<APTask__c>();
		apCreateController.apTasks.add(newAPTask1);
		apCreateController.apTasks.add(newAPTask2);
		apCreateController.apTasks.add(newAPTask3);

		apCreateController.save();

		System.assertNotEquals(null, apCreateController.getErrorMsg());

		Test.stopTest();
	}

	@IsTest
	private static void checkReferredObject() {
		Test.startTest();

		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();

		Contact contact = testUtil.createNewContact();
		Account account = testUtil.createNewAccount();
		Account account2 = testUtil.createNewAccount();
		Lead lead = testUtil.createNewLead();
		Opportunity opportunity = testUtil.createNewOpportunity();
		Case testCase = testUtil.createNewCase();
		Contract contract = testUtil.createNewContract();

		ApexPages.currentPage().getParameters().put('id', null);
		ApexPages.currentPage().getParameters().put('refId', contact.id);
		ApexPages.currentPage().getParameters().put('refType', 'Contact');

		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(new ActionPlan__c()));
		apCreateController.referedObjectInit();
		System.assertEquals('Contact', apCreateController.refType);
		String contactName = [SELECT Name FROM Contact LIMIT 1].Name;

		System.assert(apCreateController.relatedObjNameList.size() == 1);
		System.assert(apCreateController.relatedObjNameList[0].containsIgnoreCase(contactName));

		ApexPages.currentPage().getParameters().put('id', null);
		ApexPages.currentPage().getParameters().put('refId', account.Id + ',' + account2.Id);
		ApexPages.currentPage().getParameters().put('refType', null);

		apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(new ActionPlan__c()));
		apCreateController.referedObjectInit();
		System.assertEquals('Account', apCreateController.refType);

		System.assert(apCreateController.relatedObjNameList.size() == 2);

		ApexPages.currentPage().getParameters().put('id', null);
		ApexPages.currentPage().getParameters().put('refId', lead.Id);
		ApexPages.currentPage().getParameters().put('refType', 'Lead');

		apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(new ActionPlan__c()));
		apCreateController.referedObjectInit();

		System.assert(apCreateController.relatedObjNameList.size() == 1);

		ApexPages.currentPage().getParameters().put('id', null);
		ApexPages.currentPage().getParameters().put('refId', opportunity.Id);
		ApexPages.currentPage().getParameters().put('refType', 'Opportunity');

		apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(new ActionPlan__c()));
		apCreateController.referedObjectInit();

		ApexPages.currentPage().getParameters().put('id', null);
		ApexPages.currentPage().getParameters().put('refId', testCase.Id);
		ApexPages.currentPage().getParameters().put('refType', 'Case');

		apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(new ActionPlan__c()));
		apCreateController.referedObjectInit();

		System.assertEquals(1, apCreateController.relatedObjNameList.size());

		ApexPages.currentPage().getParameters().put('id', null);
		ApexPages.currentPage().getParameters().put('refId', contract.Id);
		ApexPages.currentPage().getParameters().put('refType', 'Contract');

		apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(new ActionPlan__c()));
		apCreateController.referedObjectInit();

		Test.stopTest();

		System.assertEquals(1, apCreateController.relatedObjNameList.size());
	}

	@IsTest
	private static void testSetTaskRecordType() {
		ActionPlansTestUtilities.forceHasRecordType = true;

		ActionPlansTestUtilities testutil = new ActionPlansTestUtilities();
		ActionPlan__c ap = testutil.createNewActionPlan('contact', 5);

		Test.startTest();
		Test.setCurrentPage(Page.ActionPlanCreation);
		ApexPages.currentPage().getParameters().put('id', ap.Id);
		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(new ActionPlan__c()));

		apCreateController.actionPlan.Name = testutil.createRandomWord('APName');
		apCreateController.actionPlan.StartDate__c = Date.today();
		apCreateController.actionPlan.OwnerId = Userinfo.getUserId();
		apCreateController.refreshRelatedObjectsLookUp();
		apCreateController.actionPlan.TaskRecordTypeID__c = apCreateController.getDefaultTaskRecordTypeId();
		apCreateController.actionPlan.SkipWeekends__c = true;
		apCreateController.actionPlan.SkipDay__c = 'Start of next week';

		APTask__c newAPTask = apCreateController.addTask();
		newAPTask.Subject__c = testutil.createRandomWord('subject');
		newAPTask.DaysFromStart__c = 1;
		newAPTask.User__c = UserInfo.getUserId();
		newAPTask.Type__c = 'Meeting';
		newAPTask.Priority__c = 'Normal';
		newAPTask.Minutes_Reminder__c = '510';
		apCreateController.apTasks.add(newAPTask);

		apCreateController.save();
		/* ActionPlansBatchBuilderUtilities taskBatch = new ActionPlansBatchBuilderUtilities(apCreateController.actionPlan, apTasks, null, new Set<Id>());
		 taskBatch.generateActionPlans(); */

		Test.stopTest();
		APTask__c testAPTask = [SELECT Id, Task_RecordTypeId__c, Action_Plan__c FROM APTask__c LIMIT 1];
		System.assertNotEquals(null, testAPTask.Task_RecordTypeId__c, 'Even a master record type should have been set');
		System.assertNotEquals(null, testAPTask.Action_Plan__c, 'The APTask requires an Action Plan');
	}

	@IsTest
	private static void testForceRecordTypes() {
		ActionPlansTestUtilities.forceHasRecordType = true;

		System.debug('hasrt: ' + ActionPlansUtilities.taskUsesRecordTypes);
		ActionPlansTestUtilities testutil = new ActionPlansTestUtilities();
		ActionPlan__c actionPlan = testutil.createNewActionPlan('contact', 2);

		Test.startTest();
		Test.setCurrentPage(Page.ActionPlanCreation);
		ApexPages.currentPage().getParameters().put('id', actionPlan.Id);
		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));

		Test.stopTest();
		//System.assertEquals(null, apCreateController.getDefaultTaskRecordTypeId());
		System.assert(apCreateController.taskHasRecordType);
	}

	@IsTest
	private static void testForceNoRecordTypes() {
		ActionPlansTestUtilities.forceHasRecordType = false;

		System.debug('hasrt: ' + ActionPlansUtilities.taskUsesRecordTypes);

		ActionPlansUtilities.getTaskRecordTypeStatusDefaultValues();
		ActionPlansUtilities.getTaskRecordTypePriorityDefaultValues();

		Test.startTest();

		ActionPlansTestUtilities testutil = new ActionPlansTestUtilities();

		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlan__c actionPlan = testutil.createNewActionPlan('contact', 2);

		ApexPages.currentPage().getParameters().put('id', actionPlan.Id);
		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));

		Test.stopTest();
		System.assertEquals(null, apCreateController.getDefaultTaskRecordTypeId());

		System.assert(!ActionPlansUtilities.taskUsesRecordTypes);
	}

	@IsTest
	private static void checkMaxTasks() {
		Test.startTest();
		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
		ActionPlan__c actionPlan = testUtil.createNewActionPlan('account', ActionPlansUtilities.MAX_APTASKS);

		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));
		System.assertNotEquals(null, apCreateController.relatedFieldName, 'should have lazy loaded relatedFieldName');
		System.assert(apCreateController.relatedFieldName.endsWithIgnoreCase('Account__c'), 'Should relate Account to Action Plan');

		apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));
		apCreateController.save();
		Test.stopTest();
	}

	@IsTest
	private static void checkMaxTasksError() {
		Test.startTest();
		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
		ActionPlan__c actionPlan = testUtil.createNewActionPlan('account', ActionPlansUtilities.MAX_APTASKS + 1);

		ActionPlanCreationController apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));
		System.assertNotEquals(null, apCreateController.relatedFieldName, 'should have lazy loaded relatedFieldName');
		System.assert(apCreateController.relatedFieldName.endsWithIgnoreCase('Account__c'), 'Should relate Account to Action Plan');

		apCreateController = new ActionPlanCreationController(new Apexpages.StandardController(actionPlan));
		apCreateController.getTasks();
		apCreateController.addTask();
		Test.stopTest();
		String errorMsg = apCreateController.getErrorMsg();
		System.debug(errorMsg);
		System.debug(String.valueof(ActionPlansUtilities.MAX_APTASKS));
		System.assert(errorMsg.containsIgnoreCase(String.valueOf(ActionPlansUtilities.MAX_APTASKS)));
	}
}