sfdx-source/LabsActionPlans/main/default/objects/Action_Plans_Settings__c/Action_Plans_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The basic settings for the Action Plans App</description>
    <label>Action Plans Settings</label>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/Action_Plans_Settings__c/fields/Action_Plans_Business_Hours_ID__c.field-meta.xml
<CustomField>
	<fullName>Action_Plans_Business_Hours_ID__c</fullName>
	<description>Reserved for future functionality</description>
	<inlineHelpText>ID of the Business Hours that should be used for setting Task Due Dates (if that checkbox is checked)</inlineHelpText>
	<label>Action Plans Business Hours ID</label>
	<length>18</length>
	<type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/Action_Plans_Settings__c/fields/Chatter_Object_Brag__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Object_Brag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enable Chatter FeedItem post when a New Action Plan for a record is created.</description>
    <inlineHelpText>Enable Chatter Object Brag when a New Action Plan for an object is created.</inlineHelpText>
    <label>Enable Chatter Post</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/Action_Plans_Settings__c/fields/Default_Object_on_Lead_Conversion__c.field-meta.xml
<CustomField>
	<fullName>Default_Object_on_Lead_Conversion__c</fullName>
	<defaultValue>&quot;Contact&quot;</defaultValue>
	<description>Should be Account, Opportunity, or Contact.</description>
	<inlineHelpText>When a Lead is converted, move its Action Plans to this object.</inlineHelpText>
	<label>Default Object on Lead Conversion</label>
	<length>255</length>
	<required>true</required>
	<type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/Action_Plans_Settings__c/fields/Unassigned_Task_Assigned_to_Owner__c.field-meta.xml
<CustomField>
    <fullName>Unassigned_Task_Assigned_to_Owner__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field defaults to TRUE because we assume that no matter who triggers the invoked Action Plan creation, the tasks will most likely be assigned to the owner of the parent record.</description>
    <inlineHelpText>If the Task is Unassigned in the Template, and this is Checked, the assigned User for the Task is the Owner of the Record. If this setting is unchecked, the assigned User for the Task is the Current User.</inlineHelpText>
    <label>Unassigned Task Assigned to Record Owner</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/ActionPlanTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Action Plans. Contains Action Plan Template Tasks</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Action Plan Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
	<fullName>Description__c</fullName>
	<label>Description</label>
	<description>The template description</description>
	<type>TextArea</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/fields/SkipDay__c.field-meta.xml
<CustomField>
	<fullName>SkipDay__c</fullName>
	<description>If a Due Date lands on a weekend it should be pushed to this day.</description>
	<inlineHelpText>If a Due Date lands on a weekend it should be pushed to this day.</inlineHelpText>
	<label>Default Weekend Due Dates To</label>
	<type>Picklist</type>
	<valueSet>
		<controllingField>SkipWeekends__c</controllingField>
		<restricted>true</restricted>
		<valueSetName>SkipDay</valueSetName>
	</valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/fields/SkipWeekends__c.field-meta.xml
<CustomField>
	<fullName>SkipWeekends__c</fullName>
	<defaultValue>false</defaultValue>
	<description>If selected, tasks included in an Action Plan will not be given a Due Date that falls on a weekend.</description>
	<inlineHelpText>Automatically reschedules a task that would fall on a Saturday or a Sunday to either a Monday or Friday so you can skip weekends when calculating activity start dates.</inlineHelpText>
	<label>Avoid Weekends For Due Dates</label>
	<type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/fields/TaskRecordTypeID__c.field-meta.xml
<CustomField>
	<fullName>TaskRecordTypeID__c</fullName>
	<label>Tasks Record Type</label>
	<length>18</length>
	<type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/APTemplateTask__c.object-meta.xml
<CustomObject>
    <description>Action Plan Template Task - belongs to Action Plan Template</description>
    <label>ActionPlanTemplate Task</label>
    <nameField>
        <label>Action Plan Template Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ActionPlanTemplate Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Action_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Template__c</fullName>
    <label>Action Plan Template</label>
    <referenceTo>ActionPlanTemplate__c</referenceTo>
	<description>The parent Action Plan Template</description>
    <relationshipLabel>Action Plan Template Tasks</relationshipLabel>
    <relationshipName>aptTasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Comments__c.field-meta.xml
<CustomField>
	<fullName>Comments__c</fullName>
	<label>Comments</label>
	<length>32000</length>
	<type>LongTextArea</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/DaysFromStart__c.field-meta.xml
<CustomField>
	<fullName>DaysFromStart__c</fullName>
	<inlineHelpText>This value determines the due date of the task. For tasks with no dependency, the task&apos;s due date will be offset from the plan start date. For tasks with a dependency, the due date will be offset from the expected due date of the task on which it depends.</inlineHelpText>
	<label>Days After</label>
	<precision>3</precision>
	<description>How many days from the plan start date or due date of the controlling task will this task be due?</description>
	<scale>0</scale>
	<type>Number</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Dependent__c.field-meta.xml
<CustomField>
    <fullName>Dependent__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <label>Dependent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Priority__c.field-meta.xml
<CustomField>
	<fullName>Priority__c</fullName>
	<label>Priority</label>
	<type>Picklist</type>
	<valueSet>
		<valueSetDefinition>
			<value>
				<fullName>High</fullName>
				
				<label>High</label>
			</value>
			<value>
				<fullName>Normal</fullName>
				
				<default>true</default>
				<label>Normal</label>
			</value>
			<value>
				<fullName>Low</fullName>
				
				<label>Low</label>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Reminder__c.field-meta.xml
<CustomField>
	<fullName>Reminder__c</fullName>
	<defaultValue>false</defaultValue>
	<description>Should a reminder pop-up be set?</description>
	<label>Reminder</label>
	<type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/SendEmail__c.field-meta.xml
<CustomField>
	<fullName>SendEmail__c</fullName>
	<defaultValue>false</defaultValue>
	<description>Send email notification when a Task is created.</description>
	<label>Send Email</label>
	<type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Subject__c.field-meta.xml
<CustomField>
	<fullName>Subject__c</fullName>
	<label>Subject</label>
	<description>Task Subject</description>
	<length>255</length>
	<required>true</required>
	<type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/TaskIndex__c.field-meta.xml
<CustomField>
	<fullName>TaskIndex__c</fullName>
	<label>Task Index</label>
	<precision>18</precision>
	<description>The order in which to display the AP Tasks on a page</description>
	<scale>0</scale>
	<type>Number</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/TController__c.field-meta.xml
<CustomField>
    <fullName>TController__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Controlling template task for this template task</description>
    <label>Controlling Task</label>
    <referenceTo>APTemplateTask__c</referenceTo>
    <relationshipLabel>Dependent APT Tasks</relationshipLabel>
    <relationshipName>Dependent_APT_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/SkipDay.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>End of previous week</fullName>
    </customValue>
    <customValue>
        <fullName>Start of next week</fullName>
    </customValue>
    <description>Action Plans: Adjust task due dates to avoid weekends or any other non-working day.</description>
    <masterLabel>Skip Day</masterLabel>
</GlobalValueSet>

sfdx-source/LabsActionPlans/main/default/classes/ActionPlansPostInstallScript.cls
@SuppressWarnings('PMD.AvoidGlobalModifier')
/*
Action Plans v4
David Schach 2022
https://appexchange.salesforce.com/appxListingDetail?listingId=a0N4V00000Gg6NVUAZ

Copyright (c) 2022, salesforce.com, inc.
All rights reserved.
SPDX-License-Identifier: BSD-3-Clause
For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
*/

/**
 * Install sample data on first installation
 * @since 2022
 * @author {@link [David Schach](https://github.com/dschach)}
 * @group Utilities
 */
global class ActionPlansPostInstallScript implements InstallHandler {
	/**
	 * Script to run when the managed package is installed or upgraded
	 * @author {@link [David Schach](https://github.com/dschach)}
	 * @param  context Is this a new install, an upgrade, or a push (from the developer)?
	 */
	global void onInstall(InstallContext context) {
		if (context.previousVersion() == null) {
			onFirstInstall();
		}
		// prettier-ignore
		if (context.isUpgrade()) {} //NOPMD
		// prettier-ignore
		if (context.isPush()) {} //NOPMD
	}

	/**
	 * Automated actions on first install of package
	 * <br>Create custom settings - in future, use configuration page?
	 * <br>Create sample Action Plan Template
	 * @author David Schach
	 */
	private void onFirstInstall() {
		Action_Plans_Settings__c instance = new Action_Plans_Settings__c(SetupOwnerId = UserInfo.getOrganizationId());
		instance.Action_Plans_Business_Hours_ID__c = [SELECT Id FROM BusinessHours WHERE IsDefault = TRUE][0].Id;
		instance.Default_Object_on_Lead_Conversion__c = 'Contact';
		instance.Unassigned_Task_Assigned_to_Owner__c = (Boolean) Action_Plans_Settings__c.Unassigned_Task_Assigned_to_Owner__c.getDescribe().getDefaultValue();
		instance.Chatter_Object_Brag__c = (Boolean) Action_Plans_Settings__c.Chatter_Object_Brag__c.getDescribe().getDefaultValue();
		upsert instance;

		Id defaultRTID = ActionPlansUtilities.getDefaultTaskRecordTypeId();

		ActionPlanTemplate__c apt = new ActionPlanTemplate__c();
		apt.Name = 'New Customer Onboarding';
		apt.Description__c = 'When Prospect -> Customer, do these tasks';
		apt.SkipDay__c = 'Start of next week';
		apt.SkipWeekends__c = true;
		apt.TaskRecordTypeID__c = '';
		insert apt;

		APTemplateTask__c a1 = new APTemplateTask__c(Action_Plan_Template__c = apt.Id);
		a1.Subject__c = 'Send welcome gift';
		a1.Priority__c = [SELECT Id, MasterLabel FROM TaskPriority WHERE IsHighPriority = TRUE LIMIT 1].MasterLabel;
		a1.Dependent__c = 'None';
		a1.Name = 'New Customer Onboarding - Send welcome gift';
		a1.TaskIndex__c = 0;
		a1.DaysFromStart__c = 1;
		a1.Action_Plan_Template__c = apt.Id;
		a1.Reminder__c = false;
		a1.SendEmail__c = false;
		a1.Comments__c = 'Contact our branded product provider to ship appropriate gift';
		insert a1;

		APTemplateTask__c a2 = new APTemplateTask__c(Action_Plan_Template__c = apt.Id);
		a2.Subject__c = 'Enable Customer Community User';
		a2.Priority__c = ActionPlansUtilities.getTaskRecordTypePriorityDefaultValues().get(defaultRTID);
		a2.Dependent__c = '0';
		a2.Name = 'New Customer Onboarding - Enable Customer Experience User';
		a2.TaskIndex__c = 1;
		a2.DaysFromStart__c = 2;
		a2.Action_Plan_Template__c = apt.Id;
		a2.TController__c = a1.Id;
		a2.Reminder__c = false;
		a2.SendEmail__c = false;
		insert a2;

		APTemplateTask__c a3 = new APTemplateTask__c(Action_Plan_Template__c = apt.Id);
		a3.Subject__c = 'Schedule onboarding call with customer success';
		a3.Priority__c = ActionPlansUtilities.getTaskRecordTypePriorityDefaultValues().get(defaultRTID);
		a3.Dependent__c = '1';
		a3.Name = 'New Customer Onboarding - Schedule onboarding call with customer success';
		a3.TaskIndex__c = 2;
		a3.DaysFromStart__c = 1;
		a3.Action_Plan_Template__c = apt.Id;
		a3.TController__c = a2.Id;
		a3.Reminder__c = false;
		a3.SendEmail__c = false;
		insert a3;
	}

	/**
	 * Reserved for future use
	 * @author David Schach
	 */
	// prettier-ignore
	private void onUpgrade() {} //NOPMD
	/**
	 * Reserved for future use
	 * @author David Schach
	 */
	// prettier-ignore
	private void onPush() {} //NOPMD
}