sfdx-source/LabsActionPlans/main/default/objects/Action_Plans_Settings__c/Action_Plans_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The basic settings for the Action Plans App</description>
    <label>Action Plans Settings</label>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/Action_Plans_Settings__c/fields/Chatter_Object_Brag__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Object_Brag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enable Chatter FeedItem post when a New Action Plan for a record is created.</description>
    <inlineHelpText>Enable Chatter Object Brag when a New Action Plan for an object is created.</inlineHelpText>
    <label>Enable Chatter Post</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlan__c/ActionPlan__c.object-meta.xml
<CustomObject>
    <description>Action Plan instance. Contains Action Plan Tasks.</description>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/APTask__c.object-meta.xml
<CustomObject>
    <description>Action Plan Task - belongs to Action Plan</description>
    <label>ActionPlan Task</label>
    <nameField>
        <label>ActionPlan Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ActionPlan Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Action_Plan__c.field-meta.xml
<CustomField>
	<fullName>Action_Plan__c</fullName>
	<label>Action Plan</label>
	<referenceTo>ActionPlan__c</referenceTo>
	<relationshipName>apTasks1</relationshipName>
	<relationshipOrder>0</relationshipOrder>
	<type>MasterDetail</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/ActivityDate__c.field-meta.xml
<CustomField>
	<fullName>ActivityDate__c</fullName>
	<description>The Due Date for this AP Task - will be copied to the Task Due Date</description>
	<label>Due Date</label>
	<type>Date</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Comments__c.field-meta.xml
<CustomField>
	<fullName>Comments__c</fullName>
	<label>Comments</label>
	<description>Text to be copied to Task Description</description>
	<length>32000</length>
	<type>LongTextArea</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Controller__c.field-meta.xml
<CustomField>
	<fullName>Controller__c</fullName>
	<deleteConstraint>SetNull</deleteConstraint>
	<label>Controlling Task</label>
	<referenceTo>APTask__c</referenceTo>
	<relationshipLabel>Dependent AP Tasks</relationshipLabel>
	<relationshipName>Dependent_AP_Tasks</relationshipName>
	<type>Lookup</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/DaysFromStart__c.field-meta.xml
<CustomField>
    <fullName>DaysFromStart__c</fullName>
    <inlineHelpText>This value determines the due date of the task. For tasks with no dependency, the task&apos;s due date will be offset from the plan start date. For tasks with a dependency, the due date will be offset from the expected due date of the task on which it depends.</inlineHelpText>
    <label>Days After</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Dependent__c.field-meta.xml
<CustomField>
	<fullName>Dependent__c</fullName>
	<defaultValue>&quot;None&quot;</defaultValue>
	<label>Dependent</label>
	<length>255</length>
	<description>The TaskIndex of the controlling task</description>
	<type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/IsClosed__c.field-meta.xml
<CustomField>
	<fullName>IsClosed__c</fullName>
	<defaultValue>false</defaultValue>
	<description>Set via trigger. Used in VIsualforce ActionPlanDetail page logic</description>
	<inlineHelpText>True if the task status is one of the closed statuses in this org</inlineHelpText>
	<label>Closed</label>
	<type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Minutes_Reminder__c.field-meta.xml
<CustomField>
	<fullName>Minutes_Reminder__c</fullName>
	<inlineHelpText>Minutes after midnight to show Task reminder</inlineHelpText>
	<description>Minutes after midnight to show Task reminder. Not shown to user - use the Time_Reminder formula instead.</description>
	<label>Minutes Reminder</label>
	<length>4</length>
	<type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Unrestricted picklist so can include any custom task priorities the customer may use.</description>
    <inlineHelpText>The default priority of the new task</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Reminder__c.field-meta.xml
<CustomField>
	<fullName>Reminder__c</fullName>
	<defaultValue>false</defaultValue>
	<label>Reminder</label>
	<type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/SendEmail__c.field-meta.xml
<CustomField>
    <fullName>SendEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Send Email Notification of Task creation.</description>
    <label>Send Email</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Status__c.field-meta.xml
<CustomField>
	<fullName>Status__c</fullName>
	<description>Initial Task Status. Depends on Record Type, so is unrestricted picklist.</description>
	<label>Status</label>
	<type>Picklist</type>
	<valueSet>
		<valueSetDefinition>
			<value>
				<fullName>Not Started</fullName>
				
				<label>Not Started</label>
			</value>
			<value>
				<fullName>In Progress</fullName>
				
				<label>In Progress</label>
			</value>
			<value>
				<fullName>Waiting on someone else</fullName>
				
				<label>Waiting on someone else</label>
			</value>
			<value>
				<fullName>Deferred</fullName>
				
				<label>Deferred</label>
			</value>
			<value>
				<fullName>Completed</fullName>
				
				<label>Completed</label>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Task_RecordTypeId__c.field-meta.xml
<CustomField>
	<fullName>Task_RecordTypeId__c</fullName>
	<description>Formula for setting the Record Type of the created Task</description>
	<formula>Action_Plan__r.TaskRecordTypeID__c</formula>
	<formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
	<label>Tasks Record Type Id</label>
	<type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/TaskIndex__c.field-meta.xml
<CustomField>
	<fullName>TaskIndex__c</fullName>
	<label>Task Index</label>
	<description>The order in which to display the AP Tasks on a page</description>
	<precision>18</precision>
	<scale>0</scale>
	<type>Number</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Time_Reminder__c.field-meta.xml
<CustomField>
    <fullName>Time_Reminder__c</fullName>
    <formula>IF(Reminder__c &amp;&amp; !ISBLANK(Minutes_Reminder__c),
IF(MOD(FLOOR(VALUE(Minutes_Reminder__c) / 60),12) == 0,&apos;12&apos;,TEXT(MOD(FLOOR(VALUE(Minutes_Reminder__c) / 60),12))) &amp; &apos;:&apos; &amp; IF(MOD(VALUE(Minutes_Reminder__c) ,60)==0,&apos;00&apos;,TEXT(MOD(VALUE(Minutes_Reminder__c) ,60)))+&apos; &apos;+ IF( VALUE(Minutes_Reminder__c)&gt;=720, &apos;PM&apos;,&apos;AM&apos;),

&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time Reminder</label>
    <type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/Type__c.field-meta.xml
<CustomField>
	<fullName>Type__c</fullName>
	<label>Type</label>
	<description>Task Type</description>
	<type>Picklist</type>
	<valueSet>
		<valueSetDefinition>
			<value>
				<fullName>Call</fullName>
			</value>
			<value>
				<fullName>Email</fullName>
			</value>
			<value>
				<fullName>Mail</fullName>
			</value>
			<value>
				<fullName>Meeting</fullName>
			</value>
			<value>
				<fullName>Misc</fullName>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTask__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If this field is not required, leaving it blank will assign the task to the related record owner.</inlineHelpText>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>APTasks</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/tests/ActionPlansQueueableBuilderTest.cls
/*
Action Plans v4
David Schach 2022
https://appexchange.salesforce.com/appxListingDetail?listingId=a0N4V00000Gg6NVUAZ

Action Plans v3
Force.com Labs 2011
http://appexchange.salesforce.com/listingDetail?listingId=a0N30000003HcINEA0

Copyright (c) 2022, salesforce.com, inc.
All rights reserved.
SPDX-License-Identifier: BSD-3-Clause
For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
*/
/**
 * Test for Action Plans Queueable Builder
 * @author {@link [David Schach](https://github.com/dschach)}
 * @group Tests
 * @see ActionPlansQueuableBuilder
 */
@IsTest
private class ActionPlansQueueableBuilderTest {
	@TestSetup
	private static void makeData() {
		Action_Plans_Settings__c aps = Action_Plans_Settings__c.getOrgDefaults();
		aps.Chatter_Object_Brag__c = true;
		try {
			upsert aps;
		} catch (Exception e) {
			update aps;
		}
	}

	@IsTest
	private static void runQueueContact() {
		ActionPlansTestUtilities testutil = new ActionPlansTestUtilities();

		Test.startTest();

		ActionPlan__c ap = testutil.createNewActionPlan('contact', 5);
		List<APTask__c> apTasks = [
			SELECT
				Action_Plan__c,
				ActivityDate__c,
				Comments__c,
				Controller__c,
				DaysFromStart__c,
				Dependent__c,
				Id,
				IsClosed__c,
				Minutes_Reminder__c,
				Name,
				Priority__c,
				Reminder__c,
				SendEmail__c,
				Status__c,
				Subject__c,
				TaskIndex__c,
				Task_RecordTypeId__c,
				Time_Reminder__c,
				Type__c,
				User__c
			FROM APTask__c
		];

		Contact op = new Contact();
		op.LastName = 'Doe';
		insert op;

		Contact op2 = new Contact();
		op2.LastName = 'Doe';
		insert op2;

		Set<Id> oIdsList = new Set<Id>();
		oIdsList.add(op.Id);
		oIdsList.add(op2.Id);

		ActionPlansQueueableBuilder testQueue = new ActionPlansQueueableBuilder(ap, apTasks, 'Contact', oIdsList);
		Id queueID = System.enqueueJob(testQueue);
		Test.stopTest();

		AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :queueId];
		System.assertEquals('Completed', a.status);
		System.assertEquals(0, a.NumberOfErrors);
	}

	@IsTest
	private static void runQueueException() {
		ActionPlansTestUtilities.forceError = true;
		ActionPlansTestUtilities testutil = new ActionPlansTestUtilities();

		Test.startTest();

		ActionPlan__c ap = testutil.createNewActionPlan('opportunity', 5);
		List<APTask__c> apTasks = new List<APTask__c>();

		Opportunity op = new Opportunity();
		op.Name = 'Op1';
		op.StageName = 'Won';
		op.CloseDate = Date.today();
		insert op;

		Opportunity op2 = new Opportunity();
		op2.Name = 'Op2';
		op2.StageName = 'Won';
		op2.CloseDate = Date.today();
		insert op2;

		Set<Id> oIdsList = new Set<Id>();
		oIdsList.add(op.Id);
		oIdsList.add(op2.Id);

		ActionPlansQueueableBuilder testQueue = new ActionPlansQueueableBuilder(ap, apTasks, 'Opportunity', oIdsList);
		Id queueID = System.enqueueJob(testQueue);

		Test.stopTest();

		AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :queueId];
		System.assertEquals('Completed', a.status);
		System.assertEquals(0, a.NumberOfErrors);
	}
}