sfdx-source/LabsActionPlans/main/default/objects/Action_Plans_Settings__c/Action_Plans_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>The basic settings for the Action Plans App</description>
    <label>Action Plans Settings</label>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/Action_Plans_Settings__c/fields/Unassigned_Task_Assigned_to_Owner__c.field-meta.xml
<CustomField>
    <fullName>Unassigned_Task_Assigned_to_Owner__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field defaults to TRUE because we assume that no matter who triggers the invoked Action Plan creation, the tasks will most likely be assigned to the owner of the parent record.</description>
    <inlineHelpText>If the Task is Unassigned in the Template, and this is Checked, the assigned User for the Task is the Owner of the Record. If this setting is unchecked, the assigned User for the Task is the Current User.</inlineHelpText>
    <label>Unassigned Task Assigned to Record Owner</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/ActionPlanTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Action Plans. Contains Action Plan Template Tasks</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Action Plan Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/tests/ActionPlansPostInstallScriptTest.cls
/*
Action Plans v4
David Schach 2022
https://appexchange.salesforce.com/appxListingDetail?listingId=a0N4V00000Gg6NVUAZ

Copyright (c) 2022, salesforce.com, inc.
All rights reserved.
SPDX-License-Identifier: BSD-3-Clause
For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
*/
/**
 * Test for PostInstallScript Utility
 * @author {@link [David Schach](https://github.com/dschach)}
 * @since 2022
 * @since 2023 System.assert to Assert class + error messages
 * @see ActionPlansPostInstallScript
 * @group Tests
 */
@IsTest
private class ActionPlansPostInstallScriptTest {
	@isTest
	private static void installScript() {
		ActionPlansPostInstallScript postinstall = new ActionPlansPostInstallScript();
		Test.testInstall(postinstall, null);
		Assert.areNotEqual(0, [SELECT COUNT() FROM ActionPlanTemplate__c], 'We should have created an Action Plan Template');
		Assert.areEqual(
			true,
			Action_Plans_Settings__c.getInstance().Unassigned_Task_Assigned_to_Owner__c,
			'Custom Setting Unassigned_Task_Assigned_to_Owner default is incorrect. Should be true.'
		);
		Test.testInstall(postinstall, new Version(4, 0), false);
		Test.testInstall(postinstall, new Version(4, 0), true);
	}
}