sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/ActionPlanTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Action Plans. Contains Action Plan Template Tasks</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Action Plan Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
	<fullName>Description__c</fullName>
	<label>Description</label>
	<description>The template description</description>
	<type>TextArea</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/fields/SkipDay__c.field-meta.xml
<CustomField>
	<fullName>SkipDay__c</fullName>
	<description>If a Due Date lands on a weekend it should be pushed to this day.</description>
	<inlineHelpText>If a Due Date lands on a weekend it should be pushed to this day.</inlineHelpText>
	<label>Default Weekend Due Dates To</label>
	<type>Picklist</type>
	<valueSet>
		<controllingField>SkipWeekends__c</controllingField>
		<restricted>true</restricted>
		<valueSetName>SkipDay</valueSetName>
	</valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/fields/SkipWeekends__c.field-meta.xml
<CustomField>
	<fullName>SkipWeekends__c</fullName>
	<defaultValue>false</defaultValue>
	<description>If selected, tasks included in an Action Plan will not be given a Due Date that falls on a weekend.</description>
	<inlineHelpText>Automatically reschedules a task that would fall on a Saturday or a Sunday to either a Monday or Friday so you can skip weekends when calculating activity start dates.</inlineHelpText>
	<label>Avoid Weekends For Due Dates</label>
	<type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/APTemplateTask__c.object-meta.xml
<CustomObject>
    <description>Action Plan Template Task - belongs to Action Plan Template</description>
    <label>ActionPlanTemplate Task</label>
    <nameField>
        <label>Action Plan Template Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ActionPlanTemplate Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Action_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Template__c</fullName>
    <label>Action Plan Template</label>
    <referenceTo>ActionPlanTemplate__c</referenceTo>
	<description>The parent Action Plan Template</description>
    <relationshipLabel>Action Plan Template Tasks</relationshipLabel>
    <relationshipName>aptTasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Comments__c.field-meta.xml
<CustomField>
	<fullName>Comments__c</fullName>
	<label>Comments</label>
	<length>32000</length>
	<type>LongTextArea</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/DaysFromStart__c.field-meta.xml
<CustomField>
	<fullName>DaysFromStart__c</fullName>
	<inlineHelpText>This value determines the due date of the task. For tasks with no dependency, the task&apos;s due date will be offset from the plan start date. For tasks with a dependency, the due date will be offset from the expected due date of the task on which it depends.</inlineHelpText>
	<label>Days After</label>
	<precision>3</precision>
	<description>How many days from the plan start date or due date of the controlling task will this task be due?</description>
	<scale>0</scale>
	<type>Number</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Dependent__c.field-meta.xml
<CustomField>
    <fullName>Dependent__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <label>Dependent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Minutes_Reminder__c.field-meta.xml
<CustomField>
    <fullName>Minutes_Reminder__c</fullName>
    <inlineHelpText>Minutes after midnight to show Task reminder</inlineHelpText>
    <label>Minutes Reminder</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Priority__c.field-meta.xml
<CustomField>
	<fullName>Priority__c</fullName>
	<label>Priority</label>
	<type>Picklist</type>
	<valueSet>
		<valueSetDefinition>
			<value>
				<fullName>High</fullName>
				
				<label>High</label>
			</value>
			<value>
				<fullName>Normal</fullName>
				
				<default>true</default>
				<label>Normal</label>
			</value>
			<value>
				<fullName>Low</fullName>
				
				<label>Low</label>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Reminder__c.field-meta.xml
<CustomField>
	<fullName>Reminder__c</fullName>
	<defaultValue>false</defaultValue>
	<description>Should a reminder pop-up be set?</description>
	<label>Reminder</label>
	<type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/SendEmail__c.field-meta.xml
<CustomField>
	<fullName>SendEmail__c</fullName>
	<defaultValue>false</defaultValue>
	<description>Send email notification when a Task is created.</description>
	<label>Send Email</label>
	<type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Subject__c.field-meta.xml
<CustomField>
	<fullName>Subject__c</fullName>
	<label>Subject</label>
	<description>Task Subject</description>
	<length>255</length>
	<required>true</required>
	<type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/TaskIndex__c.field-meta.xml
<CustomField>
	<fullName>TaskIndex__c</fullName>
	<label>Task Index</label>
	<precision>18</precision>
	<description>The order in which to display the AP Tasks on a page</description>
	<scale>0</scale>
	<type>Number</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/TController__c.field-meta.xml
<CustomField>
    <fullName>TController__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Controlling template task for this template task</description>
    <label>Controlling Task</label>
    <referenceTo>APTemplateTask__c</referenceTo>
    <relationshipLabel>Dependent APT Tasks</relationshipLabel>
    <relationshipName>Dependent_APT_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Type__c.field-meta.xml
<CustomField>
	<fullName>Type__c</fullName>
	<label>Task Type</label>
	<length>255</length>
	<description>Task Type</description>
	<type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/SkipDay.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>End of previous week</fullName>
    </customValue>
    <customValue>
        <fullName>Start of next week</fullName>
    </customValue>
    <description>Action Plans: Adjust task due dates to avoid weekends or any other non-working day.</description>
    <masterLabel>Skip Day</masterLabel>
</GlobalValueSet>

sfdx-source/LabsActionPlans/main/default/classes/ActionPlanTemplateExport.cls
/*
Action Plans v4
David Schach 2022
https://appexchange.salesforce.com/appxListingDetail?listingId=a0N4V00000Gg6NVUAZ

Action Plans v3
Force.com Labs 2011
http://appexchange.salesforce.com/listingDetail?listingId=a0N30000003HcINEA0

Copyright (c) 2022, salesforce.com, inc.
All rights reserved.
SPDX-License-Identifier: BSD-3-Clause
For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
*/
/**
 * Helper class to do the work for creating XML for a given Action Plan Template
 * @group Import Export
 * @since 2011
 */
public without sharing class ActionPlanTemplateExport {
	/**
	 * The `ActionPlanTemplate__c` to be exported
	 */
	private String templateId;

	/**
	 * The `File` or `Document` Id for display on the Visualforce confirmation page
	 */
	public Id fileOrDocumentId { get; private set; }

	/**
	 * Constructor
	 * @param templateId `ActionPlanTemplate__c` Id
	 */
	public ActionPlanTemplateExport(String templateId) {
		this.templateId = templateId;
	}

	/**
	 * Method in charge of handling the export task related to a Action Plan Template
	 * @author {@link [David Schach](https://github.com/dschach)}
	 * @return `ContentDocument` or `Document` Id
	 */
	public Id export() {
		ActionPlanTemplate__c apTemplate = [
			SELECT
				SkipWeekends__c,
				SkipDay__c,
				Name,
				Id,
				Description__c,
				(
					SELECT
						Id,
						Name,
						Action_Plan_Template__c,
						TController__c,
						Comments__c,
						DaysFromStart__c,
						Dependent__c,
						Type__c,
						Priority__c,
						Reminder__c,
						SendEmail__c,
						Subject__c,
						Minutes_Reminder__c,
						TaskIndex__c
					FROM aptTasks__r
				)
			FROM ActionPlanTemplate__c
			WHERE Id = :this.templateId
		];

		String xml = buildXmlString(apTemplate);

		fileOrDocumentId = ActionPlansUtilities.getIsLex() ? saveToContent(apTemplate.name, xml) : saveToDocument(apTemplate.name, xml);

		return fileOrDocumentId;
	}

	/**
	 * Method to save document in personal folder for later retrievel
	 * @author {@link [David Schach](https://github.com/dschach)}
	 * @param name
	 * @param xml
	 * @return `Id` of the new `Document`
	 */
	@TestVisible
	private Id saveToDocument(String name, String xml) {
		Document doc = new Document();
		doc.body = Blob.valueOf(xml);
		doc.ContentType = 'application/force-download';
		doc.name = 'Export - ' + name + ' - ' + System.now() + '.xml';
		doc.FolderId = UserInfo.getUserId();

		insert doc;
		return doc.Id;
	}

	/**
	 * Method to save the XML file to a File (if the user is using Lightning Experience)
	 * @author {@link [David Schach](https://github.com/dschach)}
	 * @param  name File Name
	 * @param  xml  The XML of the exported template
	 * @return      `Id` of the new `ContentDocument`
	 */
	@TestVisible
	private Id saveToContent(String name, String xml) {
		ContentVersion cv = new ContentVersion();
		cv.Title = 'Export - ' + name + ' - ' + System.now() + '.xml';
		cv.VersionData = Blob.valueof(xml);
		cv.PathOnClient = cv.Title;
		cv.OwnerId = UserInfo.getUserId();
		insert cv;

		ContentDocument cd = [SELECT LatestPublishedVersionId, Id, Title FROM ContentDocument WHERE LatestPublishedVersionId = :cv.Id];

		return cd.Id;
	}

	/**
	 * Method to compile XML document for a given Action Plan Template and child tasks
	 * @param target
	 * @return `String` The XML
	 */
	@TestVisible
	private String buildXmlString(ActionPlanTemplate__c target) {
		Xmlstreamwriter out = new Xmlstreamwriter();

		out.writeStartDocument(null, '1.0');

		out.writeStartElement(null, 'export', null);
		out.writeStartElement(null, 'meta', null);

		writeElement(out, 'exportPackage', Schema.getGlobalDescribe().get(ActionPlansUtilities.namespacePrefix + 'ActionPlanTemplate__c').getDescribe().getLabel());
		writeElement(out, 'exportAuthor', UserInfo.getName());
		writeElement(out, 'exportOrganization', UserInfo.getOrganizationName());
		writeElement(out, 'exportCreateDate', '' + System.now());

		out.writeEndElement();

		out.writeStartElement(null, 'ActionPlanTemplate', null);

		writeElement(out, 'id', target.id);
		writeElement(out, 'name', target.name);
		writeElement(out, 'description', '' + target.Description__c);
		writeElement(out, 'skipWeekend', '' + String.valueOf(target.SkipWeekends__c));
		writeElement(out, 'skipday', '' + (!target.SkipWeekends__c ? 'null' : target.SkipDay__c));

		out.writeEndElement();
		out.writeStartElement(null, 'ActionPlanTemplateTasks', null);

		for (APTemplateTask__c currentTask : target.aptTasks__r) {
			out.writeStartElement(null, 'TaskTemplate', null);
			writeElement(out, 'id', '' + currentTask.Id);
			writeElement(out, 'templateId', '' + currentTask.Action_Plan_Template__c);
			writeElement(out, 'subject', '' + currentTask.Subject__c);
			if (target.aptTasks__r.size() == 1) {
				writeElement(out, 'dependent', '' + System.Label.ap_None);
				writeElement(out, 'taskIndex', '0');
			} else {
				writeElement(out, 'dependent', '' + currentTask.Dependent__c);
				writeElement(out, 'taskIndex', '' + String.valueOf(currentTask.TaskIndex__c));
			}
			writeElement(out, 'taskcontroller', '' + currentTask.TController__c);
			writeElement(out, 'daysFromStart', '' + String.valueOf(currentTask.DaysFromStart__c));
			writeElement(out, 'category', '' + currentTask.Type__c);
			writeElement(out, 'priority', '' + currentTask.Priority__c);
			writeElement(out, 'sendEmail', '' + String.valueOf(currentTask.SendEmail__c));
			writeElement(out, 'reminder', '' + String.valueOf(currentTask.Reminder__c));
			writeElement(out, 'reminderTime', '' + currentTask.Minutes_Reminder__c);
			writeElement(out, 'comments', '' + currentTask.Comments__c);

			out.writeEndElement();
		}

		out.writeEndElement();
		out.writeEndElement();
		out.writeEndDocument();

		String ret = out.getXmlString();

		out.close();

		return ret;
	}

	/**
	 * Method used for sanitizing input for XML document
	 * @param out `Xmlstreamwriter` the XML string so far
	 * @param tag `String` XML Tag
	 * @param content `String` XML content
	 */
	private void writeElement(Xmlstreamwriter out, String tag, String content) {
		out.writeStartElement(null, tag, null);
		out.writeCharacters(EncodingUtil.urlEncode(content, 'UTF-8'));
		out.writeEndElement();
	}
}