sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/ActionPlanTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Action Plans. Contains Action Plan Template Tasks</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Action Plan Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
	<fullName>Description__c</fullName>
	<label>Description</label>
	<description>The template description</description>
	<type>TextArea</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/fields/SkipDay__c.field-meta.xml
<CustomField>
	<fullName>SkipDay__c</fullName>
	<description>If a Due Date lands on a weekend it should be pushed to this day.</description>
	<inlineHelpText>If a Due Date lands on a weekend it should be pushed to this day.</inlineHelpText>
	<label>Default Weekend Due Dates To</label>
	<type>Picklist</type>
	<valueSet>
		<controllingField>SkipWeekends__c</controllingField>
		<restricted>true</restricted>
		<valueSetName>SkipDay</valueSetName>
	</valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/ActionPlanTemplate__c/fields/SkipWeekends__c.field-meta.xml
<CustomField>
	<fullName>SkipWeekends__c</fullName>
	<defaultValue>false</defaultValue>
	<description>If selected, tasks included in an Action Plan will not be given a Due Date that falls on a weekend.</description>
	<inlineHelpText>Automatically reschedules a task that would fall on a Saturday or a Sunday to either a Monday or Friday so you can skip weekends when calculating activity start dates.</inlineHelpText>
	<label>Avoid Weekends For Due Dates</label>
	<type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/APTemplateTask__c.object-meta.xml
<CustomObject>
    <description>Action Plan Template Task - belongs to Action Plan Template</description>
    <label>ActionPlanTemplate Task</label>
    <nameField>
        <label>Action Plan Template Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ActionPlanTemplate Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Action_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan_Template__c</fullName>
    <label>Action Plan Template</label>
    <referenceTo>ActionPlanTemplate__c</referenceTo>
	<description>The parent Action Plan Template</description>
    <relationshipLabel>Action Plan Template Tasks</relationshipLabel>
    <relationshipName>aptTasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Comments__c.field-meta.xml
<CustomField>
	<fullName>Comments__c</fullName>
	<label>Comments</label>
	<length>32000</length>
	<type>LongTextArea</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/DaysFromStart__c.field-meta.xml
<CustomField>
	<fullName>DaysFromStart__c</fullName>
	<inlineHelpText>This value determines the due date of the task. For tasks with no dependency, the task&apos;s due date will be offset from the plan start date. For tasks with a dependency, the due date will be offset from the expected due date of the task on which it depends.</inlineHelpText>
	<label>Days After</label>
	<precision>3</precision>
	<description>How many days from the plan start date or due date of the controlling task will this task be due?</description>
	<scale>0</scale>
	<type>Number</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Dependent__c.field-meta.xml
<CustomField>
    <fullName>Dependent__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <label>Dependent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Minutes_Reminder__c.field-meta.xml
<CustomField>
    <fullName>Minutes_Reminder__c</fullName>
    <inlineHelpText>Minutes after midnight to show Task reminder</inlineHelpText>
    <label>Minutes Reminder</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Priority__c.field-meta.xml
<CustomField>
	<fullName>Priority__c</fullName>
	<label>Priority</label>
	<type>Picklist</type>
	<valueSet>
		<valueSetDefinition>
			<value>
				<fullName>High</fullName>
				
				<label>High</label>
			</value>
			<value>
				<fullName>Normal</fullName>
				
				<default>true</default>
				<label>Normal</label>
			</value>
			<value>
				<fullName>Low</fullName>
				
				<label>Low</label>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Reminder__c.field-meta.xml
<CustomField>
	<fullName>Reminder__c</fullName>
	<defaultValue>false</defaultValue>
	<description>Should a reminder pop-up be set?</description>
	<label>Reminder</label>
	<type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/SendEmail__c.field-meta.xml
<CustomField>
	<fullName>SendEmail__c</fullName>
	<defaultValue>false</defaultValue>
	<description>Send email notification when a Task is created.</description>
	<label>Send Email</label>
	<type>Checkbox</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Subject__c.field-meta.xml
<CustomField>
	<fullName>Subject__c</fullName>
	<label>Subject</label>
	<description>Task Subject</description>
	<length>255</length>
	<required>true</required>
	<type>Text</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/TaskIndex__c.field-meta.xml
<CustomField>
	<fullName>TaskIndex__c</fullName>
	<label>Task Index</label>
	<precision>18</precision>
	<description>The order in which to display the AP Tasks on a page</description>
	<scale>0</scale>
	<type>Number</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/TController__c.field-meta.xml
<CustomField>
    <fullName>TController__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Controlling template task for this template task</description>
    <label>Controlling Task</label>
    <referenceTo>APTemplateTask__c</referenceTo>
    <relationshipLabel>Dependent APT Tasks</relationshipLabel>
    <relationshipName>Dependent_APT_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/LabsActionPlans/main/default/objects/APTemplateTask__c/fields/Type__c.field-meta.xml
<CustomField>
	<fullName>Type__c</fullName>
	<label>Task Type</label>
	<length>255</length>
	<description>Task Type</description>
	<type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/SkipDay.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>End of previous week</fullName>
    </customValue>
    <customValue>
        <fullName>Start of next week</fullName>
    </customValue>
    <description>Action Plans: Adjust task due dates to avoid weekends or any other non-working day.</description>
    <masterLabel>Skip Day</masterLabel>
</GlobalValueSet>

sfdx-source/LabsActionPlans/main/default/classes/ActionPlanTemplateImport.cls
/*
Action Plans v4
David Schach 2022
https://appexchange.salesforce.com/appxListingDetail?listingId=a0N4V00000Gg6NVUAZ

Action Plans v3
Force.com Labs 2011
http://appexchange.salesforce.com/listingDetail?listingId=a0N30000003HcINEA0

Copyright (c) 2022, salesforce.com, inc.
All rights reserved.
SPDX-License-Identifier: BSD-3-Clause
For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
*/
/**
 * Called from ActionPlanTemplateImportController - can probably be rolled into that class, but it's doing fine here.
 * @since 2022
 * @author {@link [David Schach](https://github.com/dschach)}
 * @group Import Export
 * @see ActionPlanTemplateImportController
 */
public inherited sharing class ActionPlanTemplateImport {
	private Map<Id, APTemplateTask__c> importedTasks;
	private Map<Id, APTemplateTask__c> newTasks;

	/**
	 * Controller Constructor
	 */
	public ActionPlanTemplateImport() {
		this.importedTasks = new Map<Id, APTemplateTask__c>();
		this.newTasks = new Map<Id, APTemplateTask__c>();
	}

	/**
	 * Method in charge of retrieving and compiling the data from imported file,
	 * for then inserting into the system.
	 * @param document Attachment record
	 * @exception ImportException
	 * @return `String` Action Plan Template Id
	 */
	public String processImportedDocument(Attachment document) {
		String xml;
		ActionPlanTemplate__c apTemplate;

		//get body of text from imported document
		try {
			xml = document.body.toString();
		} catch (Exception e) {
			throw new ImportException(System.Label.ap_Errors_xmlRead);
		}

		try {
			this.readingMetaData(xml);
		} catch (Exception ex) {
			throw new ImportException(System.Label.ap_Errors_InvalidXMLTemplate);
		}

		try {
			//Get information regarding the Action Plan Template
			apTemplate = this.importAPTemplate(xml);
			//Insert Action Plan Template
			insert apTemplate;
		} catch (Exception ex) {
			throw new ImportException(System.Label.ap_Errors_ImportingXMLTemplate);
		}

		try {
			//Get information for all Tasks
			this.importAPTtasks(xml, apTemplate.Id);
			if (this.newTasks.size() > ActionPlansUtilities.MAX_APTASKS) {
				List<String> parameters = new List<String>();
				parameters.add(String.valueof(ActionPlansUtilities.MAX_APTASKS));
				throw new ImportException(String.format(System.Label.ap_Errors_TaskLimitError, parameters));
			}
			//Insert Tasks for Action Plan template
			insert newTasks.values();
		} catch (Exception ex) {
			throw new ImportException(System.Label.ap_Errors_ImportingXMLTask);
		}

		try {
			//Finish linking up dependent Tasks and updating those tasks in the system
			List<APTemplateTask__c> updatedTasks = this.setupDependentTasks();
			update updatedTasks;
		} catch (Exception ex) {
			throw new ImportException(System.Label.ap_Errors_ImportingXMLTask);
		}

		return apTemplate.Id;
	}

	/**
	 * Method for reading the meta data tag from xml document
	 * @exception ImportException
	 * @param xml String of import file
	 */
	private void readingMetaData(String xml) {
		Xmlstreamreader reader = new Xmlstreamreader(xml);
		Boolean foundMetaData = false;

		while (reader.hasNext()) {
			if (reader.getEventType() == XmlTag.START_ELEMENT && reader.getLocalName() == 'meta') {
				foundMetaData = this.parseMetaData(reader);
			}
			if (reader.getEventType() == XmlTag.END_ELEMENT && reader.getLocalName() == 'meta') {
				break;
			}
			reader.next();
		}

		if (!foundMetaData) {
			throw new ImportException(System.Label.ap_Errors_xmlMetaData);
		}
	}

	/**
	 * Handle importing of a Action Plan Template Object
	 * @param xml import file
	 * @return `ActionPlanTemplate__c` Action Plan Template
	 */
	private ActionPlanTemplate__c importAPTemplate(String xml) {
		ActionPlanTemplate__c apTemplate = new ActionPlanTemplate__c();
		Xmlstreamreader reader = new Xmlstreamreader(xml);

		while (reader.hasNext()) {
			if (reader.getEventType() == XmlTag.START_ELEMENT && reader.getLocalName() == 'ActionPlanTemplate') {
				apTemplate = this.parseTemplate(reader);
			}
			if (reader.getEventType() == XmlTag.END_ELEMENT && reader.getLocalName() == 'ActionPlanTemplate') {
				break;
			}
			reader.next();
		}

		return apTemplate;
	}

	/**
	 * Handle importing of Action Plan Template Task Objects
	 * @param xml import file
	 * @param apTemplateId Action Plan Template Id
	 */
	private void importAPTtasks(String xml, Id apTemplateId) {
		Xmlstreamreader reader = new Xmlstreamreader(xml);

		while (reader.hasNext()) {
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'TaskTemplate') {
				this.parseTemplateTask(reader, apTemplateId);
			}
			if (reader.getEventType() == XMLTag.END_ELEMENT && reader.getLocalName() == 'ActionPlanTemplateTasks') {
				break;
			}
			reader.next();
		}
	}

	/**
	 * Parse metadata from XMl document
	 * @param reader
	 * @exception ImportException
	 * @return `Boolean` correctMetaData
	 */
	private Boolean parseMetaData(Xmlstreamreader reader) {
		Boolean correctMetaData = true;

		while (reader.hasNext()) {
			//handle name field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'exportPackage') {
				reader.next();
				String packageName = getDecodedString(reader);
				if (packageName == '') {
					correctMetaData = false;
					throw new ImportException(System.Label.ap_Errors_xmlMetaData);
				}
			}
			//handle Author field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'exportAuthor') {
				reader.next();
				String author = getDecodedString(reader);
				if (author == '') {
					correctMetaData = false;
					throw new ImportException(System.Label.ap_Errors_xmlMetaData);
				}
			}
			//handle skipWeekend field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'exportOrganization') {
				reader.next();
				String organization = getDecodedString(reader);
				if (organization == '') {
					correctMetaData = false;
					throw new ImportException(System.Label.ap_Errors_xmlMetaData);
				}
			}
			//handle skipday field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'exportCreateDate') {
				reader.next();
				String createdDate = getDecodedString(reader);
				if (createdDate == '') {
					correctMetaData = false;
					throw new ImportException(System.Label.ap_Errors_xmlMetaData);
				}
			}

			if (reader.getEventType() == XMLTag.END_ELEMENT && reader.getLocalName() == 'meta') {
				break;
			}
			reader.next();
		}

		return correctMetaData;
	}

	/**
	 * Parse data from XMl document to create a Action Plan Template Object
	 * @param reader
	 * @return `ActionPlanTemplate__c` The created Action Plan Template
	 */
	private ActionPlanTemplate__c parseTemplate(Xmlstreamreader reader) {
		ActionPlanTemplate__c apTemplateAux = new ActionPlanTemplate__c();

		while (reader.hasNext()) {
			//handle name field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'name') {
				reader.next();
				apTemplateAux.Name = getDecodedString(reader);
			}
			//handle Description field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'description') {
				reader.next();
				String descValue = getDecodedString(reader);
				if (descValue == 'null') {
					apTemplateAux.Description__c = '';
				} else {
					apTemplateAux.Description__c = descValue;
				}
			}
			//handle skipWeekend field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'skipWeekend') {
				reader.next();
				apTemplateAux.SkipWeekends__c = Boolean.valueOf(getDecodedString(reader));
			}
			//handle skipday field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'skipday') {
				reader.next();
				//apTemplateAux.SkipDay__c = getDecodedString( reader );
				String sdValue = getDecodedString(reader);
				if (sdValue == 'null') {
					apTemplateAux.SkipDay__c = '';
				} else {
					apTemplateAux.SkipDay__c = sdValue;
				}
			}

			//validate that we're done
			if (apTemplateAux.Name != null && apTemplateAux.Description__c != null && apTemplateAux.SkipWeekends__c != null && apTemplateAux.SkipDay__c != null) {
				reader.next();
				break;
			}

			reader.next();
		}

		return apTemplateAux;
	}

	/**
	 * Parse data from XMl document to create a Template Task Object
	 * @param reader       XML reader
	 * @param apTemplateId template Id
	 */
	private void parseTemplateTask(Xmlstreamreader reader, Id apTemplateId) {
		APTemplateTask__c apTaskAux = new APTemplateTask__c();

		apTaskAux.Action_Plan_Template__c = apTemplateId;
		String currentTaskOldId = '';

		while (reader.hasNext()) {
			//handle Id field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'id') {
				reader.next();
				currentTaskOldId = getDecodedString(reader);
			}
			//handle subject field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'subject') {
				reader.next();
				apTaskAux.Subject__c = getDecodedString(reader);
			}
			//handle dependent field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'dependent') {
				reader.next();
				apTaskAux.Dependent__c = getDecodedString(reader);
			}
			//handle task index field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'taskindex') {
				reader.next();
				apTaskAux.TaskIndex__c = Decimal.valueOf(getDecodedString(reader));
			}
			//handle apttemplate field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'taskcontroller') {
				reader.next();
				String referenceId = getDecodedString(reader);
				if (referenceId != 'null') {
					apTaskAux.TController__c = referenceId;
				}
			}
			//handle daysFromStart field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'daysFromStart') {
				reader.next();
				apTaskAux.DaysFromStart__c = Decimal.valueOf(getDecodedString(reader));
			}
			//handle category field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'category') {
				reader.next();
				String taskType = getDecodedString(reader);
				if (taskType != 'null') {
					apTaskAux.Type__c = taskType;
				}
			}
			//handle priority field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'priority') {
				reader.next();
				apTaskAux.Priority__c = getDecodedString(reader);
			}
			//handle sendEmail field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'sendEmail') {
				reader.next();
				apTaskAux.SendEmail__c = Boolean.valueOf(getDecodedString(reader));
			}
			//handle reminder field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'reminder') {
				reader.next();
				apTaskAux.Reminder__c = Boolean.valueOf(getDecodedString(reader));
			}
			//handle reminderTime field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'reminderTime') {
				reader.next();
				apTaskAux.Minutes_Reminder__c = getDecodedString(reader);
			}
			//handle comments field
			if (reader.getEventType() == XMLTag.START_ELEMENT && reader.getLocalName() == 'comments') {
				reader.next();
				String commentValue = getDecodedString(reader);
				if (commentValue != 'null') {
					apTaskAux.Comments__c = commentValue;
				}
			}
			if (reader.getEventType() == XMLTag.END_ELEMENT && reader.getLocalName() == 'TaskTemplate') {
				break;
			}
			reader.next();
		}

		//Add relevant information to Maps for later completing linking between dependent tasks
		this.importedTasks.put(currentTaskOldId, apTaskAux);
		//Note: removing APTemplateTask__c reference field to be able to insert tasks.
		APTemplateTask__c clonedTask = apTaskAux.clone();
		clonedTask.TController__c = null;
		this.newTasks.put(currentTaskOldId, clonedTask);
	}

	/**
	 * Method in charge of re-building dependent tasks for imported Action Plans Template
	 * @return `List<APTemplateTask__c>` updatedTasks
	 */
	private List<APTemplateTask__c> setupDependentTasks() {
		//list for returning updated tasks
		List<APTemplateTask__c> updatedTasks = new List<APTemplateTask__c>();
		//get all old ids as keys from recently imported and inserted tasks
		Set<Id> keys = this.newTasks.keySet();

		for (Id key : keys) {
			APTemplateTask__c auxNewTask = this.newTasks.get(key);
			APTemplateTask__c auxOldTask = this.importedTasks.get(key);

			//checks to see if task has a reference to another task
			if (auxOldTask.TController__c != null) {
				if (String.valueOf(auxOldTask.TController__c).length() != 0) {
					Id auxRefId = auxOldTask.TController__c;
					//get dependent task
					APTemplateTask__c auxRefTask = this.newTasks.get(auxRefId);
					//Update task reference
					auxNewTask.TController__c = auxRefTask.Id;
				}
			}
			updatedTasks.add(auxNewTask);
		}

		return updatedTasks;
	}

	/**
	 * Method for decoding strings from XML document
	 * @param reader Part of the XML string
	 * @return String
	 */
	private String getDecodedString(Xmlstreamreader reader) {
		return EncodingUtil.urlDecode(reader.getText(), 'UTF-8').trim();
	}

	// prettier-ignore
	public class ImportException extends Exception {} //NOPMD
}